<?php

  if($this->session->userdata('email'))
  {
    include('usernav.php');
  }
  else
  {
   include('navbar.php');
  }
?>

<div class="container-fluid abt-banner" style="padding:0;">
<div class="abt-banner-dark">
</div>
</div>

<div class="container-fluid">
<div class="container">
<div class="abt-info">
<ol class="breadcrumb mx-crumb">
<li><a href="index.htm">Home</a></li>
<li><a href="#">Management</a></li>
<li class="active">MBA India</li>
</ol>
<div class="abt-details">

<div class="row">

<div class=" col-md-3 col-xs-12"> <!-- required for floating -->
<!-- Nav tabs -->
<ul class="nav nav-tabs tabs-left">
<li class="active"><a href="#step1" data-toggle="tab">MBA in India</a></li>
<li><a href="#step2" data-toggle="tab">List of Colleges of PGDM</a></li>
<li><a href="#step3" data-toggle="tab">List of Colleges of MBA</a></li>
</ul>
</div>
<div class=" col-xs-12 col-md-9">
<!-- Tab panes -->
<div class="tab-content">
<div class="tab-pane active" id="step1">

<div style="margin-bottom:20px;">
<h4 class="tabpane-head1">MBA Admission in India / Management Admission in India</h4>
<p>Students from Various parts of the nation are taking up the opportunities to doing with Management education in India deals with various Type of managerial activities. Employees do task in a group to complete activities for particular objective. Managers are the professional and skilled who user different resources to achieve desired objective of the Company.</p>
<p><strong>Eligibility Management Education-</strong> Students can find two type of Management Education in India. Type one is <strong>Under Graduate course</strong> and other is <strong>Post Graduate Course</strong>.
</p>
<p>For Bachelors/ UnderGraduate Course to get admission, the student must qualify 12th or Higher Secondary Examination or Equivalent Examination. This Course is Non as Bachelor in Management and duration of study period 3 years. Students who have completed their Bachelors degree from Central/State Universities or any other Recognized University, they are eligible for Masters in Management. Now a days Reputed Institutions Have mandatory to qualify Entrance Examination like Have mandatory to qualify Entrance Examination like- <strong>CAT,MAT,CMAT,ATMA,XAT,GMAT,SNAP,NMAT,IIFT,CET,State Universities Entrance Examination and other Management Entrance Examinations (As per direction by University, College, Institutions & Etc)</strong>.
</p>
<p><strong>Eligibility Criteria-</strong> For Bachelors in Management, Candidate must pass 12th or Equivalent degree or Equivalent course recognized by Central/State/ Other Recognized Board with 45 %( 40 % for SC/ST/Other Quota if applicable as per Institution Norms).</p>
<p>For Masters in  Management, Candidate must pass Bachelor’s degree or Equivalent Degree from any Recognized University at least 50 %( 45% for SC,ST, other Quota if applicable as per Institution Norms).</p>
</div>

<div style="margin-bottom:20px;">
<h5 class="tabpane-head1">Importance of Management Education in India-
</h5>
<p>It is the best and uplift stream where students from any recognized stream can easily get an enrollment. The concentration of Management Education in India is associated with live practical, analytical and work floor practice as well as theoretical concept of Business Management. Students who have become MBA from Reputed Institution can easily get themselves to any filled of work.
</p>
</div>

<div style="margin-bottom:20px;">
<h5 class="tabpane-head">Recognized By / Affiliation By</h5>
<ul class="tab-panelist">
<li>UGC Recognized, AICTE Approved, Ministry of HRD, NAAC Accredited.</li>
<li>Career Counseling & Admission Guidance for Top Management Education in India for 2018-19 Session (BBA/MBA/PGDM)</li>
<li>A management degree from a reputed institution certifies that the person holding the degree has enough managerial skills required to face the competition. Management courses develops skillful workforce which constitutes of leaders of future as well as competitive managers. They have the ability to handle complex business situations.
</li>
<li>Affinity provides Service which will answer all your queries and make your dreams a reality. Our experienced team advises students on educational opportunities in the top Management Colleges. Furthermore, we assist you with the admission process and provide guidance on career choices.
</li>
</ul>
</div>

</div>

<div class="tab-pane" id="step2">
<h4 class="tabpane-head1">Colleges of PGDM</h4>

<table class="table table-striped mx-table">
 
<tbody>
</tbody><thead> 
<tr> 
<th>COLLEGE NAME</th> 
<th>Location</th> 
</tr> 
</thead> 

<tbody>
<tr>
<td>ANUGRAH NARAYAN COLLEGE, PATNA</td>
<td>BIHAR</td>
</tr>
<tr>
<td>MILLIA INSTITUTE OF TECHNOLOGY</td>
<td>BIHAR</td>
</tr>
<tr>
<td>R.P.SHARMA INSTITUTE OF TECHNOLOGY</td>
<td>BIHAR</td>
</tr>
<tr>
<td>DEPARTMENT OF BUSINESS ADMINISTRATION</td>
<td>BIHAR</td>
</tr>
<tr>
<td>J. D. WOMEN'S COLLEGE</td>
<td>BIHAR</td>
</tr>
<tr>
<td>VAISHALI INSTITUTE OF BUSINESS & RURAL MANAGEMENT</td>
<td>BIHAR</td>
</tr>
<tr>
<td>CHANDRAGUPT INSTITUTE OF MANAGEMENT PATNA</td>
<td>BIHAR</td>
</tr>
<tr>
<td>NALANDA COLLEGE</td>
<td>BIHAR</td>
</tr>
<tr>
<td>GOVERNMENT WOMENS POLYTECHNIC</td>
<td>BIHAR</td>
</tr>
<tr>
<td>DEPARTMENT OF BUSINESS ADMINISTRATION (SSC)</td>
<td>BIHAR</td>
</tr>
<tr>
<td>UNIVERSITY DEPARTMENT OF COMMERCE AND BUSINESS ADMINISTRATION</td>
<td>BIHAR</td>
</tr>
<tr>
<td>B. S. COLLEGE</td>
<td>BIHAR</td>
</tr>
<tr>
<td>SIWAN ENGINEERING & TECHNICAL INSTITUTE SIWAN</td>
<td>BIHAR</td>
</tr>
<tr>
<td>L. N. MISHRA INSTITUTEOF ECONOMIC DEVELOPMENT AND SOCIAL CHANGE</td>
<td>BIHAR</td>
</tr>
<tr>
<td>B. D. COLLEGE</td>
<td>BIHAR</td>
</tr>
<tr>
<td>INSTITUTE OF BUSINESS MANAGEMENT, BELA, DARBHANGA</td>
<td>BIHAR</td>
</tr>
<tr>
<td>L.N.MISHRA COLLEGE OF BUSINESS MANAGEMENT</td>
<td>BIHAR</td>
</tr>
<tr>
<td>COLLEGE OF COMMERCE, PATNA</td>
<td>BIHAR</td>
</tr>
<tr>
<td>DEVELOPMENT MANAGEMENT INSTITUTE</td>
<td>BIHAR</td>
</tr>
<tr>
<td>INTERNATIONAL SCHOOL OF MANAGEMENT PATNA</td>
<td>BIHAR</td>
</tr>
<tr>
<td>BIRLA INSTITUTE OF TECHNOLOGY, PATNA</td>
<td>BIHAR</td>
</tr>

<tr>
<td>REGIONAL INSTITUTE OF COOPERATIVE MANAGEMENT</td>
<td>CHANDIGARH</td>
</tr>
<tr>
<td>GOVT.POLYTECHNIC FOR WOMEN</td>
<td>CHANDIGARH</td>
</tr>
<tr>
<td>GITARATTAN INTERNATIONAL BUSINESS SCHOOL</td>
<td>DELHI</td>
</tr>
<tr>
<td>GITARATTAN INTERNATIONAL BUSINESS SCHOOL</td>
<td>DELHI</td>
</tr>
<tr>
<td>GURU NANAK INSTITUTE OF MANAGEMENT</td>
<td>DELHI</td>
</tr>
<tr>
<td>RUKMINI DEVI INSTITUTE OF ADVANCED STUDIES</td>
<td>DELHI</td>
</tr>
<tr>
<td>TERI UNIVERSITY</td>
<td>DELHI</td>
</tr>
<tr>
<td>FORE SCHOOL OF MANAGEMENT</td>
<td>DELHI</td>
</tr>
<tr>
<td>APEEJAY SCHOOL OF MANAGEMENT</td>
<td>DELHI</td>
</tr>

<tr>
<td>INTERNATIONAL INSTITUTE OF HEALTH MANAGEMENT RESEARCH</td>
<td>DELHI</td>
</tr>
<tr>
<td>LAL BAHADUR SHASTRI INSTITUTE OF MANAGEMENET, DELHI</td>
<td>DELHI</td>
</tr>
<tr>
<td>MAHARAJA AGRASEN INSTITUTE OF TECHNOLOGY</td>
<td>DELHI</td>
</tr>
<tr>
<td>DELHI INSTITUTE OF ADVANCED STUDIES</td>
<td>DELHI</td>
</td>
</tr>
<tr>
<td>MANAGEMENT EDUCATION AND RESEARCH INSTITUTE</td>
<td>DELHI</td>
</tr>
<tr>
<td>NEW DELHI INSTITUTE OF MANAGEMENT</td>
<td>DELHI</td>
</tr>
<tr>
<td>TECNIA INSTITUTE OF ADVANCED STUDIES</td>
<td>DELHI</td>
</tr>
<tr>
<td>"INSTITUTE OF MARKETING & MANAGEMENT - BUSINESS SCHOOL"</td>
<td>DELHI</td>
</tr>
<tr>
<td>ENTREPRENEURSHIP & MANAGEMENT PROCESSES INTERNATIONAL</td>
<td>DELHI</td>
</tr>
<tr>
<td>BHAI PARMANAND INSTITUTE OF BUSINESS STUDIES</td>
<td>DELHI</td>
</tr>
<tr>
<td>BANARSIDAS CHANDIWALA INSTITUTE OF PROFESSIONAL STUDIES</td>
<td>DELHI</td>
</tr>
<tr>
<td>JAGANNATH INTERNATIONAL MANAGEMENT SCHOOL</td>
<td>DELHI</td>
</tr>
<tr>
<td>HMR INSTITUTE OF TECHNOLOGY AND MANAGEMENT</td>
<td>DELHI</td>
</tr>
<tr>
<td>ERA BUSINESS SCHOOL</td>
<td>DELHI</td>
</tr>
<tr>
<td>BHAGWAN PARSHURAM INSTITUTE OF TECHNOLOGY</td>
<td>DELHI</td>
</tr>
<tr>
<td>INTERNATIONAL MANAGEMENT INSTITUTE</td>
<td>DELHI</td>
</tr>
<tr>
<td>JAGAN INSTITUTE OF MANAGEMENT STUDIES TECHNICAL CAMPUS</td>
<td>DELHI</td>
</tr>
<tr>
<td>SRI SHARADA INSTITUTE OF INDIAN MANAGEMENT RESEARCH</td>
<td>DELHI</td>
</tr>
<tr>
<td>INDIAN INSTITUTE OF TOURISM AND TRAVEL MANAGEMENT NEW DELHI</td>
<td>DELHI</td>
</tr>
<tr>
<td>BHARATI VIDYAPEETH UNIVERSITY INSTITUTE OF MANAGEMENT AND RESEARCH</td>
<td>DELHI</td>
</tr>
<tr>
<td>MEERABAI INSTITUTE OF TECHNOLOGY</td>
<td>DELHI</td>
</tr>
<tr>
<td>PERIYAR MANAGEMENT AND COMPUTER COLLEGE</td>
<td>DELHI</td>
</tr>
<tr>
<td>INSTITUTE OF INFORMATION TECHNOLOGY & MANAGEMENT</td>
<td>DELHI</td>
</tr>
<tr>
<td>VIVEKANANDA INSTITUTE OF PROFESSIONAL STUDIES- TECHNICAL CAMPUS</td>
<td>DELHI</td>
</tr>
<tr>
<td>SRI SUKHMANI INSTITUTE OF MANAGEMENT</td>
<td>DELHI</td>
</tr>
<tr>
<td>DPC INSTITUTE OF MANAGEMENT</td>
<td>DELHI</td>
</tr>
<tr>
<td>DELHI COLLEGE OF ENGINEERING</td>
<td>DELHI</td>
</tr>
<tr>
<td>JAMIA HAMDARD</td>
<td>DELHI</td>
</tr>
<tr>
<td>ASIA-PACIFIC INSTITUTE OF MANAGEMENT</td>
<td>DELHI</td>
</tr>
<tr>
<td>INTERNATIONAL MANAGEMENT CENTRE</td>
<td>DELHI</td>
</tr>
<tr>
<td>NORTHERN INDIA ENGINEERING COLLEGE</td>
<td>DELHI</td>
</tr>
<tr>
<td>FORTUNE INSTITUTE OF INTERNATIONAL BUSINESS</td>
<td>DELHI</td>
</tr>
<tr>
<td>JAMIA MILLIA ISLAMIA (A CENTRAL UNIVERSITY)</td>
<td>DELHI</td>
</tr>
<tr>
<td>CENTRE FOR MANAGEMENT EDUCATION-AIMA</td>
<td>DELHI</td>
</tr>
<tr>
<td>IILM INSTITUTE FOR HIGHER EDUCATION</td>
<td>DELHI</td>
</tr>

<tr>
<td>GURGAON INSTITUTE OF TECHNOLOGY AND MANAGEMENT</td>
<td>HARYANA</td>
</tr>
<tr>
<td>DAV INSTITUTE OF MANAGEMENT</td>
<td>HARYANA</td>
</tr>
<tr>
<td>R.N. COLLEGE OF ENGINEERING & TECHNOLOGY</td>
<td>HARYANA</td>
</tr>
<tr>
<td>ASIA PACIFIC INSTITUTE OF INFORMATION TECHNOLOGY SD INDIA PANIPAT</td>
<td>HARYANA</td>
</tr>
<tr>
<td>N. C. COLLEGE OF ENGINEERING</td>
<td>HARYANA</td>
</tr>
<tr>
<td>GANPATI BUSSINESS SCHOOL</td>
<td>HARYANA</td>
</tr>
<tr>
<td>KIIT COLLEGE OF ENGINEERING</td>
<td>HARYANA</td>
</tr>
<tr>
<td>BLS INSTITUTE OF TECHNOLOGY MANAGEMENT</td>
<td>HARYANA</td>
</tr>
<tr>
<td>KALPI INSTITUTE OF TECHNOLOGY</td>
<td>HARYANA</td>
</tr>
<tr>
<td>KURUKSHETRA INSTITUTE OF TECHNOLOGY & MANAGEMENT</td>
<td>HARYANA</td>
</tr>
<tr>
<td>SHRI ATMANAND JAIN INSTITUTE OF MANAG EMENT & TECHNOLOGY(MBA & MCA)</td>
<td>HARYANA</td>
</tr>
<tr>
<td>SBMN INSTITUTE OF MANAGEMENT STUDIES & RESEARCH</td>
<td>HARYANA</td>
</tr>
<tr>
<td>G.V.M. INSTITUTE OF TECHNOLOGY & MANAGEMENT (FOR GIRLS)</td>
<td>HARYANA</td>
</tr>
<tr>
<td>AL- FALAH SCHOOL OF ENGINEERING & TECHNOLOGY</td>
<td>HARYANA</td>
</tr>
<tr>
<td>PANCHKULA ENGINEERING COLLEGE</td>
<td>HARYANA</td>
</tr>
<tr>
<td>MANAV RACHNA COLLEGE OF ENGINEERING</td>
<td>HARYANA</td>
</tr>
<tr>
<td>ASIAN INSTITUTE OF MANAGEMENT AND TECHNOLOGY</td>
<td>HARYANA</td>
</tr>
<tr>
<td>SATYA COLLEGE OF ENGINEERING & TECHNOLOGY</td>
<td>HARYANA</td>
</tr>
<tr>
<td>ADVANCED INSTITUTE OF TECHNOLOGY AND MANAGEMENT</td>
<td>HARYANA</td>
</tr>
<tr>
<td>CBS GROUP OF INSTITUTIONS</td>
<td>HARYANA</td>
</tr>
<tr>
<td>INSTITUTE OF TECHNOLOGY & SCIENCE</td>
<td>HARYANA</td>
</tr>
<tr>
<td>B.S.ANANGPURIA INSTITUTE OF TECHNOLOGY & MANAGEMENT</td>
<td>HARYANA</td>
</tr>
<tr>
<td>SHREE SIDDHIVINAYAK EDUCATIONAL TRUST'S GROUP OF INSTITUTIONS</td>
<td>HARYANA</td>
</tr>
<tr>
<td>JAN NAYAK CH. DEVILAL INSTITUTE OF BUSINESS MG</td>
<td>HARYANA</td>
</tr>
<tr>
<td>DELHI INSTITUTE OF TECHNOLOGY & MANAGEMENT</td>
<td>HARYANA</td>
</tr>
<tr>
<td>SAT PRIYA GROUP OF INSTITUTIONS</td>
<td>HARYANA</td>
</tr>
<tr>
<td>APPLIED COLLEGE OF MANAGEMENT & ENGINEERING (ACME)</td>
<td>HARYANA</td>
</tr>
<tr>
<td>ROYAL INSTITUTE OF MANAGEMENT & TECHNOLOGY</td>
<td>HARYANA</td>
</tr>
<tr>
<td>SCHOOL OF ENGINEERING AND TECHNOLOGY</td>
<td>HARYANA</td>
</tr>
<tr>
<td>VAISH COLLEGE OF ENGINEERING</td>
<td>HARYANA</td>
</tr>
<tr>
<td>WORLD COLLEGE OF TECHNOLOGY AND MANAGEMENT</td>
<td>HARYANA</td>
</tr>
<tr>
<td>GURGAON COLLEGE OF ENGINEERING</td>
<td>HARYANA</td>
</tr>
<tr>
<td>JAN NAYAK CH. DEVI LAL MEMORIAL COLLEGE OF ENGINEERING</td>
<td>HARYANA</td>
</tr>
<tr>
<td>DOON VALLEY INSTITUTE OF COMPUTER APPLICATIONS</td>
<td>HARYANA</td>
</tr>
<tr>
<td>MAA OMWATI INSTITUTE OF MANAGEMENT & TECHNOLOGY</td>
<td>HARYANA</td>
</tr>
<tr>
<td>OM INSTITUTE OF TECHNOLOGY & MANAGEMENT</td>
<td>HARYANA</td>
</tr>
<tr>
<td>KEDARNATH AGGARWAL INSTITUTE OF MANAGEMENT</td>
<td>HARYANA</td>
</tr>
<tr>
<td>MODERN INSTITUTE OF ENGG. AND TECHNOLOGY</td>
<td>HARYANA</td>
</tr>
<tr>
<td>R.P. INDERAPRASTHA INSTITUTE OF TECHNOLOGY</td>
<td>HARYANA</td>
</tr>
<tr>
<td>MR DAV INSTITUTE OF MANAGEMENT STUDIES</td>
<td>HARYANA</td>
</tr>
<tr>
<td>NAV NIRMAN SEWA SAMITI'S SAMALKHA GROUP OF INSTITUTIONS</td>
<td>HARYANA</td>
</tr>
<tr>
<td>MATU RAM INSTITUTE OF MANAGEMENT</td>
<td>HARYANA</td>
</tr>
<tr>
<td>TILAK RAJ CHADHA INSTITUTE OF MGMT. & TECH.</td>
<td>HARYANA</td>
</tr>
<tr>
<td>ARAVALI COLLEGE OF ENGINEERING & MANAGEMENT</td>
<td>HARYANA</td>
</tr>
<tr>
<td>SHRI KRISHAN INSTITUTE OF ENGINEERING AND TECHNOLOGY</td>
<td>HARYANA</td>
</tr>
<tr>
<td>YAMUNA INSTITUTE OF ENGINEERING & TECHNOLOGY</td>
<td>HARYANA</td>
</tr>
<tr>
<td>MM ENGINEERING COLLEGE, MULLANA- AMBALA</td>
<td>HARYANA</td>
</tr>
<tr>
<td>BHIWANI INSTITUTE OF TECHNOLOGY AND SCIENCES</td>
<td>HARYANA</td>
</tr>
<tr>
<td>GURU NANAK INSTITUTE OF MANAGEMENT</td>
<td>HARYANA</td>
</tr>
<tr>
<td>GANGA INSTITUTE OF TECHNOLOGY AND MANAGEMENT</td>
<td>HARYANA</td>
</tr>
<tr>
<td>SD INSTITUTE OF MANAGEMENT AND TECHNOLOGY</td>
<td>HARYANA</td>
</tr>
<tr>
<td>B M GROUP OF INSTITUTIONS</td>
<td>HARYANA</td>
</tr>
<tr>
<td>P.D.MEMORIAL COLLEGE OF ENGINEERING</td>
<td>HARYANA</td>
</tr>
<tr>
<td>HINDU INSTITUTE OF MANAGEMENT</td>
<td>HARYANA</td>
</tr>
<tr>
<td>BHARAT INSTITUTE OF TECHNOLOGY, SONEPAT</td>
<td>HARYANA</td>
</tr>
<tr>
<td>SOMANY (P.G) INSTITUTE OF TECHNOLOGY AND MANAGEMENT</td>
<td>HARYANA</td>
</tr>
<tr>
<td>RAWAL INSTITUTE OF MANAGEMENT</td>
<td>HARYANA</td>
</tr>
<tr>
<td>MAHARISHI MARKANDESHWAR GROUP OF INSTITUTIONS</td>
<td>HARYANA</td>
</tr>
<tr>
<td>NGF COLLEGE OF ENGINEERING & TECHNOLOGY</td>
<td>HARYANA</td>
</tr>
<tr>
<td>SETH JAI PARKASH MUKAND LAL INSTITUTE OF ENGINEERING & TECHNOLOGY</td>
<td>HARYANA</td>
</tr>
<tr>
<td>GANPATI INSTITUTE OF TECHNOLOGY & MANAGEMENT</td>
<td>HARYANA</td>
</tr>
<tr>
<td>NATIONAL POWER TRAINING INSTITUTE</td>
<td>HARYANA</td>
</tr>
<tr>
<td>SWAMI DEVI DYAL INSTITUTE OF ENGINEERING</td>
<td>HARYANA</td>
</tr>
<tr>
<td>SHREE RAM MULKH INSTITUTE OF ENGINEERING & TECHNOLOGY</td>
<td>HARYANA</td>
</tr>
<tr>
<td>TECHNOLOGY EDUCATION & RESEARCH INSTITUTE</td>
<td>HARYANA</td>
</tr>
<tr>
<td>GALAXY GLOBAL EDUCATIONAL TRUST'S GROUP OF INSTITUTIONS</td>
<td>HARYANA</td>
</tr>
<tr>
<td>MAHARAJA AGRASEN INSTITUTE OF MANAGEMENT AND TECHNOLOGY</td>
<td>HARYANA</td>
</tr>
<tr>
<td>PANIPAT INSTITUTE OF ENGINEERING & TECHNOLOGY</td>
<td>HARYANA</td>
</tr>
<tr>
<td>KESHAV INSTITUTE OF MANAGEMENT</td>
<td>HARYANA</td>
</tr>
<tr>
<td>TEK CHAND MANN COLLEGE OF ENGINEERING</td>
<td>HARYANA</td>
</tr>
<tr>
<td>GURU JAMBHESHWAR UNIVERSITY OF SCIENCE & TECHNOLOGY</td>
<td>HARYANA</td>
</tr>
<tr>
<td>RATTAN INSTITUTE OF TECHNOLOGY & MANAGEMENT</td>
<td>HARYANA</td>
</tr>
<tr>
<td>D. R . COLLEGE OF ENGINEERING & TECHNOLOGY</td>
<td>HARYANA</td>
</tr>
<tr>
<td>SAVERA EDUCATIONAL TRUST GROUP OF INSTITUTIONS</td>
<td>HARYANA</td>
</tr>
<tr>
<td>KARNAL INSTITUTE OF TECHNOLOGY & MANAGEMENT</td>
<td>HARYANA</td>
</tr>
<tr>
<td>BHAGWAN MAHAVEER INSTITUTE OF ENGINEERING AND TECHNOLOGY, SONEPAT</td>
<td>HARYANA</td>
</tr>
<tr>
<td>REGIONAL INSTITUTE OF MANAGEMENT</td>
<td>HARYANA</td>
</tr>
<tr>
<td>BRIJ MOHAN INSTITUTE OF MANAGEMENT AND TECHNOLOGY</td>
<td>HARYANA</td>
</tr>
<tr>
<td>DELHI TECHNICAL CAMPUS</td>
<td>HARYANA</td>
</tr>
<tr>
<td>DELHI GLOBAL INSTITUTE OF MANAGEMENT</td>
<td>HARYANA</td>
</tr>
<tr>
<td>DELHI COLLEGE OF TECHNOLOGY & MANAGEMENT</td>
<td>HARYANA</td>
</tr>
<tr>
<td>VINAYAK INSTITUTE OF MANAGEMENT</td>
<td>HARYANA</td>
</tr>
<tr>
<td>SHAHEED BHAGAT SINGH INSTITUTE OF MANAGEMENT & TECHNOLOGY</td>
<td>HARYANA</td>
</tr>
<tr>
<td>KNS WORLD MANAGEMENT COLLEGE</td>
<td>HARYANA</td>
</tr>
<tr>
<td>SETH BANARSI DASS INSTITUTE OF MANAGEMENT AND TECHNOLOGY</td>
<td>HARYANA</td>
</tr>
<tr>
<td>SHREE RAM INSTITUTE OF BUSINESS & MANAGMENT</td>
<td>HARYANA</td>
</tr>
<tr>
<td>DEPARTMENT OF BUSINESS MANAGEMENT</td>
<td>HARYANA</td>
</tr>
<tr>
<td>MAHARISHI MARKANDESHWAR TECHNICAL CAMPUS</td>
<td>HIMACHAL PRADESH</td>
</tr>
<tr>
<td>KLBDAV GIRLS COLLEGE FOR MANAGEMENT</td>
<td>HIMACHAL PRADESH</td>
</tr>
<tr>
<td>HIMALAYAN INSTITUTE OF MANAGEMENT</td>
<td>HIMACHAL PRADESH</td>
</tr>
<tr>
<td>GOVT. PG COLLEGE DHARAMSHALA</td>
<td>HIMACHAL PRADESH</td>
</tr>
<tr>
<td>HP INSTITUTE OF MANAGEMENT STUDIES</td>
<td>HIMACHAL PRADESH</td>
</tr>
<tr>
<td>ETERNAL UNIVERSITY, AKAL COLLEGE OF ENGINEERING AND TECHNOLOGY</td>
<td>HIMACHAL PRADESH</td>
</tr>
<tr>
<td>L. R. INSTITUTE OF MANAGEMENT</td>
<td>HIMACHAL PRADESH</td>
</tr>
<tr>
<td>GOVT. PG COLLEGE UNA (HP)</td>
<td>HIMACHAL PRADESH</td>
</tr>
<tr>
<td>SSM COLLEGE OF ENGINEERING</td>
<td>JAMMU & KASHMIR</td>
</tr>
<tr>
<td>MODEL INSTITUTE OF ENGINEERING AND TECHNOLOGY</td>
<td>JAMMU & KASHMIR</td>
</tr>
<tr>
<td>INSTITUTE OF MANAGEMENT SCIENCES</td>
<td>JAMMU & KASHMIR</td>
</tr>
<tr>
<td>IQBAL INSTITUTE OF TECHNOLOGY AND MANAGEMENT</td>
<td>JAMMU & KASHMIR</td>
</tr>
<tr>
<td>THE BUSINESS SCHOOL</td>
<td>JAMMU & KASHMIR</td>
</tr>
<tr>
<td>ISLAMIC UNIVERSITY OF SCIENCE AND TECHNOLOGY</td>
<td>JAMMU & KASHMIR</td>
</tr>
<tr>
<td>PRESTIGE INSTITUTE OF INSTITUTE OF MANAGEMENT AND RESEARCH</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>ITM GROUP OF INSTITUTIONS (TECHNICAL CAMPUS)</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>PIONEER INSTITUTE OF PROFESSIONAL STUDIES</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>INSTITUTE OF CO OPERATIVE MANAGEMENT</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>APEX INSTITUTE OF MANAGEMENT & RESEARCH</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>UNIVERSITY INSTITUTE OF MANAGEMENT, R.D UNIVERSITY, JABALPUR</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>PATEL INSTITUTE OF TECHNOLOGY</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>BHARATIYA VIDYA MANDIR COLLEGE OF MANAGEMENT EDUCATION</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>PATEL COLLEGE OF MANAGEMENT</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>SWAMI VIVEKANAND COLLEGE OF ENGINEERING</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>S.S.H.C. JAIN INSTITUTE OF MANAGEMENT & RESEARCH</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>SHRI VAISHNAV INSTITUTE OF TECHNOLOGY & SCIENCE,</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>SAGAR INSTITUTE OF SCIENCE & TECHNOLOGY (SISTEC)</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>SHRIRAM INSTITUTE OF INFORMATION TECHNOLOGY</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>INDIAN INSTITUTE OF TOURISM AND TRAVEL MANAGEMENT GWALIOR</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>PATEL COLLEGE OF SCIENCE & TECHNOLOGY</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>CHAMELI DEVI GROUP OF INSTITUTIONS</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>PEOPLES INSTITUTE OF MANAGEMENT AND RESEARCH</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>NAGAJI INSTITUTE OF TECHNOLOGY & MANAGEMENT, GWALIOR</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>INSTITUTE OF MANAGEMENT STUDIES</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>RKDF INSTITUTE OF BUSINESS MANAGEMENT</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>ARIHANT INSTITUTE OF MANAGEMENT AND TECHNOLOGY</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>MANDSAUR INSTITUTE OF TECHNOLOGY</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>SYNERGY INSTITUTE OF TECHNOLOGY. DEWAS</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>INDIRA PRIYADARSHINI COLLEGE OF MANAGEMENT</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>SUSHILA DEVI BANSAL COLLEGE OF TECHNOLOGY</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>VINDHYA INSTITUTE OF MANAGEMENT & RESEARCH</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>TECHNOCRATS INSTITUTE OF TECHNOLOGY (EXCELLENCE)</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>MODERN INSTITUTE OF PROFESSIONAL STUDIES</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>BHABHA COLLEGE OF ENGINEERING, BHOPAL</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>TECHNOCRATS INSTITUE OF TECHNOLOGY & SCIENCE</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>INDIAN INSTITUTE OF FOREST MANAGEMENT</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>BHABHA ENGINEERING RESEARCH INSTITUTE -MCA</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>BOSTON COLLEGE FOR PROFESSIONAL STUDIES</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>INDORE INDIRA INSTITUTE OF BUSINESS MANAGEMENT</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>LAKSHMI NARAIN COLLEGE OF TECHNOLOGY</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>RADHARAMAN ENGINEERING COLLEGE</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>M L B GOVT INSTITUTION OF MANAGEMENT COLLEGE GWALIOR M P</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>BHABHA MANAGEMENT RESEARCH INSTITUTE</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>RKDF SCHOOL OF ENGINEERING</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>PRIYATAM INSTITUTE OF TECHNONLOGY AND MANAGMENT</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>MEDI-CAPS INSTITUTE OF TECHNO - MANAGEMENT</td>
<td>MADHYA PRADESH</td></td>
</tr>
<tr>
<td>VINDHYA INSTITUTE OF TECHNOLOGY & SCIENCE</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>VINDHYA INSTITUTE OF MANAGEMENT & RESEARCH</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>MATHURADEVI INSTITUTE OF TECHNOLOGY & MANAGEMENT</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>SUSHILA DEVI BANSAL COLLEGE OF ENGINEERING</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>SCHOOL OF COMPUTERS AND ELECTRONICS IPS ACADEMY</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>VINDHYA INSTITUTE OF TECHNOLOGY AND SC</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>MATHURADEVI INSTITUTE OF MANAGEMENT</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>INDORE INDIRA BUSINESS SCHOOL</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>SAMRAT ASHOK TECHNOLOGICAL INSTITUTE</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>GITS (GWALIOR INSTITUTE OF TECHNOLOGY AND SCIENCE)</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>DIVINE INTERNATIONAL GROUP OF INSTITUTIONS</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>MALWA INSTITUTE OF TECHNOLOGY</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>SAGAR INSTITUTE OF RESEARCH & TECHNOLOGY</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>SANGHVI INNOVATIVE ACADEMY,INDORE</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>BHABHA INSTITUTE OF MANAGEMENT</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>GYAN GANGA INSTITUTE OF TECHNOLOGY & MANAGEMENT</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>GICTS COLLEGE OF PROFESSIONAL EDUCATION</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>SRI AUROBINDO INSTITUTE OF MANAGEMENT & SCIENCE</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>VNS BUSINESS SCHOOL</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>RAJIV GANDHI VOCATIONAL EDUCATION & TRAINING COLLEGE</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>NATIONAL INSTITUTE OF TECHNICAL TEACHERS' TRAINING AND RESEARCH</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>INSTITUTE OF PROFESSIONAL EDUCATION AND RESEARCH (PGDM)</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>LAKSHMI NARAIN ACADEMY OF MANAGEMENT</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>PRESTIGE INSTITUTE OF MANAGEMENT</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>SANGHVI INSTITUTE OF MANAGEMENT AND SCIENCE (PGDM)</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>SAHIB INSTITUTE OF MANAGEMENT AND RESEARCH INDORE</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>SHRI RAM INSTITUTE OF TECHNOLOGY</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>VIDYASAGAR INSTITUTE OF MANAGEMENT</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>BM COLLEGE OF TECHNOLOGY</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>IES COLLEGE OF TECHNOLOGY, BHOPAL</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>REWA INSTITUTE OF TECHNOLOGY, REWA (M.P.)</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>AISECT UNIVERSITY INSTITUTE OF SCIENCE AND TECHNOLOGY</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>LORD KRISHNA COLLEGE OF TECHNOLOGY,INDORE</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>SCOPE COLLEGE OF ENGINEERING, BHOPAL</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>PRASHANTI INSTITUTE OF MANAGEMENT</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>SAM COLLEGE OF MANAGMENT AND TECHNOLOGY</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>GOVINDRAM SEKSARIA INSTITUTE OF MANAGEMENT & RESEARCH</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>KAILASH NARAYAN PATIDAR COLLEGE OF SCIENCE & TECHNOLOGY, BHOPAL</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>RUKMANI DEVI INSTITUTE OF SCIENCE & TECHNOLOGY</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>JAI NARAIN COLLEGE OF TECHNOLOGY</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>S.G.B.M. INSTITUTE OF TECHNOLOGY & SCIENCE</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>ORIENTAL COLLEGE OF MANAGEMENT, BHOPAL</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>BM COLLEGE OF MANAGEMENT & RESEARCH.</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>MADHUBAN INSTITUTE OF PROFESSIONAL STUDIES</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>LAXMIPATI INSTITUTE OE SCIENCE &TECHNOLOGY BHOPAL</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>ALPINE INSTITUTE OF TECHNOLOGY</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>SAM COLLEGE OF ENGINEERING AND TECHNOLOGY, BHOPAL</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>ACROPOLIS INSTITUTE OF TECHNOLOGY AND RESEARCH</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>MAHARISHI CENTRE FOR EDUCATIONAL EXCELLENCE</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>CORE BUSINESS SCHOOL</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>CH INSTITUTE OF MANAGEMENT & COMMERCE</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>GYANODAYA INSTITUTE OF MANAGEMENT & TECHNOLOGY</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>INSTITUTE OF ENGINEERING & SICENCE, IPS ACADEMY, INDORE</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>STAR ACADEMY OF TECHNOLOGY & MANAGEMENT, INDORE</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>CRIM,UTD,BARKATULLAH UNIVERSITY,BHOPAL</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>JAIPURIA INSTITUTE OF MANAGEMENT, INDORE</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>ADITYA COLLEGE OF TECHNOLOGY & SCIENCE</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>MAHARAJA RANJIT SINGH GROUP OF INSTITUTIONS</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>ROYAL COLLEGE OF TECHNOLOGY</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>SURABHI GROUP OF INSTITUTIONS</td>
<td>MADHYA PRADESH</td>
</tr>
<tr>
<td>VIKRANT INSTITUTE OF BUSINESS MANAGEMENT</td>
<td>MADHYA PRADESH</td>
</tr>

<!--SURABHI COLLEGE OF ENGINEERING AND TECHNOLOGY
MADHYA PRADESH
SHRI YOGINDRA SAGAR INSTITUTE OF TECHNOLOGY & SCIENCE
MADHYA PRADESH
SCHOOL OF STUDIES IN COMMERCE AND MANAGEMENT
MADHYA PRADESH
MAHARAJA INSTITUTE OF MANAGEMENT AND TECHNOLOGY
MADHYA PRADESH
SATYAM EDUCATION AND SOCIAL WELFARE SOCIETY GROUP OF INSTITUTIONS
MADHYA PRADESH
ALIA INSTITUTE OF MANAGEMENT
MADHYA PRADESH
ACADEMY OF MANAGMENT
MADHYA PRADESH
PT. JAWAHARLAL NEHRU INSTITUTE OF BUSINESS MANAGEMENT
MADHYA PRADESH
VENKTESHWAR INSTITUTE OF TECHNOLOGY
MADHYA PRADESH
V.M.GOVERNMENT POLYTECHNIC COLLEGE NARSINGHPUR MP
MADHYA PRADESH
SHRI VAISHNAV INSITUTE OF MANEGMENT
MADHYA PRADESH
GOVT.WOMENS POLYTECHNIC COLLEGE SEHORE
MADHYA PRADESH
SRI SATYA SAI INSTITUTE OF SCIENCE & TECHNOLOGY
MADHYA PRADESH
TRINITY INSTITUTE OF TECHNOLOGY & RESEARCH
MADHYA PRADESH
JAWAHARLAL NEHRU COLLEGE OF TECHNOLOGY
MADHYA PRADESH
LAKSHMI NARAIN COLLEGE OF TECHNOLOGY
MADHYA PRADESH
CH INSTITUTE OF BUSINESS STUDIES
MADHYA PRADESH
SHRI RGP GUJARATI PROFESSIONAL INSTITUTE, INDORE
MADHYA PRADESH
MAKHANLAL CHATURVEDI NATIONAL UNIVERSITY OF JOURNALISM
MADHYA PRADESH
VNS GROUP OF INSTITUTIONS
MADHYA PRADESH
RAJEEV GANDHI PROUDYOGIKI MAHAVIDYALAYA
MADHYA PRADESH
RADHADEVI RAMCHANDRA MANGAL SCHOOL OF MANAGEMENT & RESEARCH
MADHYA PRADESH
TECHNOCRATS INSTITUTE OF TECHNOLOGY
MADHYA PRADESH
RISHIRAJ INSTITUTE OF TECHNOLOGY, INDORE
MADHYA PRADESH
CRESCENT INSTITUTE OF MANAGEMENT, BHOPAL
MADHYA PRADESH
TAKSHSHILA INSTITUTE OF ENGINEERING & TECHNOLOGY, JABALPUR
MADHYA PRADESH
JAIN COLLEGE
MADHYA PRADESH
NRI INSTITUTE OF TECHNOLOGY & MANAGEMENT
MADHYA PRADESH
ROYAL INSTITUTE OF MANAGEMENT AND ADVANCED STUDIES
MADHYA PRADESH
MAHAKAL INSTITUTE OF MANAGEMENT.
MADHYA PRADESH
ACROPOLIS FACULTY OF MANAGEMENT & RESEARCH
MADHYA PRADESH
ASTRAL INSTITUTE OF TECHNOLOGY AND
MADHYA PRADESH
MANJULA K PONDA COLLEGE OF MANAGEMENT
MADHYA PRADESH
INDORE INSTITUTE OF MANAGEMENT AND RESEARCH
MADHYA PRADESH
SHRI RAM INSTITUTE OF TECHNOLOGY (MCA)
MADHYA PRADESH
SAPIENT INSTITUTE OF MANAGEMENT STUDIES
MADHYA PRADESH
VIP COLLEGE OF MANAGEMENT BHOPAL
MADHYA PRADESH
JAGRAN INSTITUTE OF COMMUNICATION & MANAGEMENT
MADHYA PRADESH
INDORE MANAGEMENT INSTITUTE AND RESEARCH CENTRE
MADHYA PRADESH
INDORE MANAGEMENT INSTITUTE AND RESEARCH CENTRE
MADHYA PRADESH
CAREER COLLEGE OF MANAGEMENT
MADHYA PRADESH
SHRI G.S.INSTITUTE OF TECH. & SCIENCE
MADHYA PRADESH
VIKRANT INSTITUTE OF MANAGEMENT
MADHYA PRADESH
FACULTY OF RURAL DEVELOPMENT AND BUSINESS ADMINISTRATION
MADHYA PRADESH
HITKARNI COLLEGE OF ENGINEERING & TECHNOLOGY
MADHYA PRADESH
MJP GOVERNMENT POLYTECHNIC COLLEGE, KHANDWA
MADHYA PRADESH
DEPARTMENT OF BUSINESS ADMINISTRATION
MADHYA PRADESH
VIKRANT INSTITUTE OF TECHNOLOGY & MANAGEMENT
MADHYA PRADESH
SRI SATYA SAI INSTITUTE OF MANAGEMENT.
MADHYA PRADESH
RKDF INSTITUTE OF MANAGEMENT
MADHYA PRADESH
GIRDHAR SHIKSHA EVAM SAMAJ KALYAN SAMITI GROUP OF INSTITUTIONS
MADHYA PRADESH
MAHARANA PRATAP COLLEGE OF TECHNOLOGY
MADHYA PRADESH
RKDF COLLEGE OF TECHNOLOGY & RESEARCH
MADHYA PRADESH
INSTITUTE OF PROFESSIONAL EDUCATIONAL RESEARCH (IPER)
MADHYA PRADESH
CENTRAL INDIA INSTITUTE OF TECHNOLOGY
MADHYA PRADESH
INSTITUTE OF BUSINESS MANAGEMENT AND RESEARCH
MADHYA PRADESH
LAL BAHADUR SHASTRI INSTITUTE OF TECHNOLOGY AND MANAGEMENT
MADHYA PRADESH
SRI PARASHURAM INSTITUTE OF TECHNOLOGY AND RESEARCH
MADHYA PRADESH
HOSHIARPUR INSTITUTE OF MANAGEMENT AND TECHNOLOGY
PUNJAB
SRI SUKHMANI INSTITUTE OF ENGINEERING & TECHNOLOGY
PUNJAB
SANT LONGOWAL INSTITUTE OF ENGINEERING & TECHNOLOGY
PUNJAB
THAPAR UNIVERSITY
PUNJAB
M K EDUCATION SOCIETIE'S GROUP OF INSTITUTIONS
PUNJAB
GURUKUL VIDYAPEETH INSTITUTE OF ENGINEERING & TECHNOLOGY
PUNJAB
SHAHEED BHAGAT SINGH STATE TECHNICAL CAMPUS
PUNJAB
SWAMI VIVEKANAND INSTITUTE OF ENGG. & TECH.
PUNJAB
SRI SAI COLLEGE OF ENGG. & TECH
PUNJAB
CGC- GROUP OF COLLEGES
PUNJAB
BHAI GURDAS INSTITUTE OF ENGINEERING & TECHNOLOGY
PUNJAB
SAI INSTITUTE OF ENGINEERING & TECHNOLOGY,MANAWALA, AMRITSAR
PUNJAB
GOVT. POLYTECHNIC COLLEGE MOHALI(KHUNI MAJRA)
PUNJAB
S. R. S. GOVT. POLYTECHNIC COLLEGE FOR GIRLS
PUNJAB
S.SUKHJINDER SINGH ENGINEERING & TECHNOLOGY COLLEGE
PUNJAB
RAYAT GROUP OF INSTITUTIONS , ROPAR
PUNJAB
KCL INSTITUTE OF MANAGEMENT AND TECHNOLOGY
PUNJAB
MALOUT INSTITUTE OF MANAGEMENT AND INFORMATION TECHNOLOGY, MALOUT
PUNJAB
DORAHA INSITUTE OF MANAGEMENT & TECHNOLOGY
PUNJAB
MATA GUJRI COLLEGE FATEHGARH SAHIB
PUNJAB
S.S.D.WOMEN'S INSTITUTE OF TECHNOLOGY
PUNJAB
SWAMI SATYANAND COLLEGE OF MANAGEMENT AND TECHNOLOGY
PUNJAB
RAYAT & BAHRA INSTITUTE OF ENGINEERING & BIO- TECHNOLOGY
PUNJAB
RAM DEVI JINDAL EDUCATIONAL CHARITABLE SOCIETY GROUP OF INSTIUTIONS
PUNJAB
ADESH INSTITUTE OF ENGINEERING & TECHNOLOGY, FARIDKOT
PUNJAB
CHITKARA INSTITUTE OF ENGINEERING & TECHNOLOGY
PUNJAB
GURU NANAK DEV ENGINEERING COLLEGE
PUNJAB
ST. SOLDIER GROUP OF INSTITUTIONS
PUNJAB
CT INSTITUTE OF ADVANCE MANAGEMENT STUDIES
PUNJAB
LUDHIANA GROUP OF COLLEGES
PUNJAB
SAS INSTITUTE OF INFORMATION TECHNOLOGY & RESEARCH (MBA COLLEGE)
PUNJAB
CT INSTITUTE OF MANAGEMENT & IT
PUNJAB
SANT BABA BHAG SINGH INSTITUTE OF ENGG. & TECHNOLOGY
PUNJAB
CONTINENTAL INSTITUTE OF ENGINEERING AND TECHNOLOGY
PUNJAB
BIS COLLEGE OF ENGINEERING & TECHNOLOGY
PUNJAB
BABA FARID COLLEGE OF MANAGEMENT & TECHNOLOGY
PUNJAB
KC COLLEGE OF ENGINEERING & INFORMATION TECHNOLOGY, NAWANSHAHR
PUNJAB
ST. SOLDIER MANAGEMENT AND TECHNICAL INSTITUTE
PUNJAB
SAS INSTITUTE OF INFORMATION TECHNOLOGY & RESEARCH(MCA COLLEGE)
PUNJAB
BHAI GURDAS INSTITUTE OF MANAGEMENT & TECHNOLOGY, SANGRUR(MBA)
PUNJAB
DESH BHAGAT FOUNDATION GROUP OF INSTITUTIONS, FEROZPUR ROAD MOGA
PUNJAB
CHANDIGARH BUSINESS SCHOOL
PUNJAB
APEEJAY SVRAN INSTITUTE OF MANAGEMENT
PUNJAB
SWIFT TECHNICAL CAMPUS
PUNJAB
GURU HARKRISHAN GIRLS COLLEGE
PUNJAB
CHANDIGARH ENGINEERING COLLEGE
PUNJAB
PUNJAB COLLEGE OF TECHNICAL EDUCATION
PUNJAB
RIMT MAHARAJA AGGRASEN ENGINEERING COLLEGE
PUNJAB
A.S.GROUP OF INSTITUTIONS
PUNJAB
MAI BHAGO GOVT POLYTECHNIC COLLEGE FOR GIRLS, AMRITSAR
PUNJAB
APEEJAY INSTITUTE OF MANAGEMENT
PUNJAB
GNA INSTITUTE OF MANAGEMENT AND TECHNOLOGY
PUNJAB
PATEL INSTITUTE OF MANAGEMENT & TECHNOLOGY
PUNJAB
GIAN JYOTI GROUP OF INSTITUTIONS
PUNJAB
A & M INSTITUTE OF MANAGEMENT AND TECHNOLOGY
PUNJAB
CGC TECHNICAL CAMPUS - FACULTY OF MANAGEMENT
PUNJAB
GGS COLLEGE OF MODERN TECHNOLOGY
PUNJAB
DOABA INSTITUTE OF ENGG. & TECH.
PUNJAB
DR I T SCHOOL OF BUSINESS
PUNJAB
RIMT-INSTITUTE OF MANAGEMENT & COMPUTER TECHNOLOGY
PUNJAB
CORDIA INSTITUTE OF BUSINESS MANAGEMENT
PUNJAB
DAV INSTITUTE OF ENGINEERING & TECHNOLOGY
PUNJAB
DR.I.T.INSTITUTE OF MANAGEMENT & TECHNOLOGY
PUNJAB
PUNJAB INSTITUTE OF MANAGEMENT & TECHNOLOGY
PUNJAB
GLOBAL INSTITUTE OF MANAGEMENT AND EMERGING TECHNOLOGIES
PUNJAB
LUDHIANA COLLEGE OF ENGINEERING & TECHNOLOGY, KATANI KALAN, LUDHIANA.
PUNJAB
RAYAT & BAHRA INSTITUTE OF MANAGEMENT
PUNJAB
SACHDEVA ENGINEERING COLLEGE FOR GIRLS
PUNJAB
LALA LAJPAT RAI MEMORIAL INSTITUTE OF MANAGEMENT & TECHNOLOGY
PUNJAB
GIAN JYOTI INSTITUTE OF MANAGEMENT & TECHNOLOGY
PUNJAB
GOVT. POLYTECHNIC COLLEGE FOR GIRLS
PUNJAB
DOABA KHALSA TRUST GROUP OF INSTITUTIONS
PUNJAB
DOABA WOMEN INSTIUTE OF ENGINEERING & TECHNOLOGY
PUNJAB
ARYANS BUSINESS SCHOOL (ABS)
PUNJAB
GURU NANAK INSTITUTE OF MANAGEMENT & TECHNOLOGY
PUNJAB
KHALSA INSTITUTE OF MANAGEMENT & TECHNOLOGY FOR WOMEN
PUNJAB
BAHRA GROUP OF INSTITUTION
PUNJAB
GOVT.POLYTECHNIC COLLEGE FOR GIRLS JALANDHAR
PUNJAB
SWAMI PARMANAND COLLEGE OF ENGG & TECH
PUNJAB
PCTE GROUP OF INSTITUTES
PUNJAB
INSTITUTE OF MANAGEMENT STUDIES- BHADDAL
PUNJAB
COLLEGE OF MANAGEMENT AND TECHNOLOGY
PUNJAB
BHARAT GROUP OF COLLEGES
PUNJAB
SAI INSTITUTE OF MANAGEMENT, MANAWALA, AMRITSAR
PUNJAB
SATYAM INSTITUTE OF MANAGEMENT AND TECHNOLOGY
PUNJAB
SIDANA INSTITUTE OF MANAGEMENT AND TECHNOLOGY
PUNJAB
BALRAJ SINGLA EDUCATIONAL SOCIETY'S GROUP OF INSTITUTIONS
PUNJAB
RAYAT BAHRA INSTITUTE OF MANAGEMENT
PUNJAB
AMRITSAR COLLEGE OF ENGINEERING & TECHNOLOGY, AMRITSAR
PUNJAB
RAMGARHIA INSTITUTE OF ENGINEERING & TECHNOLOGY
PUNJAB
KINGS GROUP OF INSTITUTIONS
PUNJAB
UNIVERSAL GROUP OF INSTITUTIONS
PUNJAB
VMS INSTITUTE OF MANAGEMENT BATALA
PUNJAB
ASRA INSTITUTE OF ADVANCED STUDIES (MBA)
PUNJAB
JASDEV SINGH SANDHU INSTITUTE OF ENGINEERING & TECHNOLOGHY
PUNJAB
FEROZEPUR INSTITUTE OF MANAGEMENT
PUNJAB
NORTH WEST INSTITUTE OF ENGINEERING & TECHNOLOGY
PUNJAB
CT INSTITUTE OF MANAGEMENT STUDIES
PUNJAB
CENTRE FOR MANAGEMENT STUDIES
PUNJAB
SECT GROUP OF INSTITUTES
PUNJAB
SURYA WORLD TECHNICAL CAMPUS
PUNJAB
SURYA EDUCATIONAL AND CHARITABLE TRUST GROUP OF INSTITUTES
PUNJAB
CAREER POINT TECHNICAL CAMPUS
PUNJAB
CKD INSTITUTE OF MANAGEMENT AND TECHNOLOGY
PUNJAB
GUJRANWALA GURU NANAK INSTITUTE OF MANGEMENT & TECHNOLOGY
PUNJAB
BHUTTA COLLEGE OF ENGINEERING & TECHNOLOGY
PUNJAB
CHANDIGARH GROUP OF COLLEGES
PUNJAB
INNOCENT HEARTS GROUP OF INSTITUTIONS
PUNJAB
GURU TEG BAHADUR KHALSA INSTITUTE OF ENGINEERING & TECHNOLOGY
PUNJAB
GLOBAL INSTITUTE OF MANAGEMENT
PUNJAB
DIPS INSTITUTE OF MANAGEMENT & TECHNOLOGY
PUNJAB
AKAL GROUP OF TECHNICAL AND MANAGEMENT INSTITUTIONS
PUNJAB
RIMT-INSTITUTE OF ENGINEERING AND TECHNOLOGY
PUNJAB
SWAMI SARVANAND INSTITUTE OF MANAGEMENT & TECHNOLOGY
PUNJAB
GULZAR GROUP OF INSTITUTIONS
PUNJAB
RATTAN PROFESSIONAL EDUCATION COLLEGE
PUNJAB
PATIALA INSTITUTE OF ENGG AND TECHNOLOGY FOR WOMEN
PUNJAB
CHANDIGARH BUSINESS SCHOOL OF ADMINISTRATION
PUNJAB
CT INSTIUTTE OF ENGINEERING, MANAGEMENT & TECHNOLOGY
PUNJAB
SHAHEED UDHAM SINGH COLLEGE OF ENGINEERING & TECHNOLOGY
PUNJAB
BABA BANDA SINGH BAHADUR ENGINEERING COLLEGE
PUNJAB
LALA LAJPAT RAI INSTITUTE OF ENGGNEERING & TECHNOLOGY
PUNJAB
BHAI MAHA SINGH COLLEGE OF ENGINEERING
PUNJAB
ARYABHATTA GROUP OF INSTITUTES,BARNALA
PUNJAB
AKLIA EDUCATIONAL AND RESEARCH SOCIETY GROUP OF INSTITUTIONS
PUNJAB
CKD INSTITUTE OF MANAGEMENT & TECHNOLOGY
PUNJAB
DEV RAJ GROUP'S TECHNICAL CAMPUS
PUNJAB
KHALSA COLLEGE(ASR) OF TECHNOLOGY AND BUSINESS STUDIES
PUNJAB
IITT COLLEGE OF ENGINEERING POJEWAL PB
PUNJAB
GEETANJALI INSTITUTE OF TECHNICAL STUDIES
RAJASTHAN
ACME INSTITUTE OF MANAGEMENT & TECHNOLOGY
RAJASTHAN
MJRP COLLEGE OF ENGINEERING AND TECHNOLOGY
RAJASTHAN
AISHWARYA COLLEGE OF MANAGEMENT & RESEARCH CENTRE
RAJASTHAN
SHRINATHJI INSTITUTE OF TECHNOLOGY & ENGINEERING
RAJASTHAN
INTERNATIONAL SCHOOL OF INFORMATICS & MANAGEMENT
RAJASTHAN
SHEKHAWATI INSTITUTE OF TECHNOLOGY
RAJASTHAN
SHEKHAWATI BUSINESS SCHOOL
RAJASTHAN
SRI BALAJI COLLEGE OF ENGINEERING & TECHNOLOGY, JAIPUR
RAJASTHAN
SHANKARA INTERNATIONAL SCHOOL OF MANAGEMENT
RAJASTHAN
SHANKARA INTERNATIONAL SCHOOL OF MANAGEMENT AND RESEARCH
RAJASTHAN
MAHARISHI ARVIND INSTITUTE OF SCIENCE AND MANAGEMENT
RAJASTHAN
SHANKARA INSTITUTE OF MANAGEMENT
RAJASTHAN
MAHARISHI ARVIND INST. OF SCIENCE AND MGMT (PGDM)
RAJASTHAN
SHANKARA INSTITUTE OF TECHNOLOGY
RAJASTHAN
KHANDELWAL VAISH GIRLS INSTITUTE OF TECHNOLOGY
RAJASTHAN
MAHARISHI ARVIND INTERNATIONAL INSTITUTE OF TECHNOLOGY
RAJASTHAN
ARYA COLLEGE OF ENGINEERING AND RESEARCH CENTRE
RAJASTHAN
BUDDHA GROUP OF INSTITUTIONS
RAJASTHAN
VYAS INSTITUTE OF MANAGEMENT
RAJASTHAN
NORTHERN INSTITUTE OF ENGINEERING TECHNICAL CAMPUS
RAJASTHAN
TAXILA BUSINESS SCHOOL
RAJASTHAN
SRI GANGANAGAR ENGINEERING COLLEGE
RAJASTHAN
JODHPUR NATIONAL UNIVERSITY
RAJASTHAN
JAIPURIA INSTITUTE OF MANAGEMENT
RAJASTHAN
GOVERNMENT ENGINEERING COLLEGE BHARATPUR
RAJASTHAN
BIYANI INSTITUTE OF SCIENCE & MANAGEMENT
RAJASTHAN
RAJASTHAN COLLEGE OF ENGINEERING FOR WOMEN
RAJASTHAN
JAIPUR NATIONAL UNIVERSITY (SCH. OF ENGG. & TECH.)
RAJASTHAN
SIDDHI VINAYAK COLLEGE OF SCIENCE & HR. EDUCATION
RAJASTHAN
LAXMI DEVI INSTITUTE OF ENGINEERING AND TECHNOLOGY
RAJASTHAN
L.T.R. INSTITUTE OF MANAGMENT
UTTAR PRADESH
CENTRE FOR DEVELOPMENT OF ADVANCED COMPUTING, NOIDA
UTTAR PRADESH
VISHVESHWARYA GROUP OF INSTITUTIONS
UTTAR PRADESH
DEWAN V.S. INSTITUTE OF ENGINEERING & TECHNOLOGY
UTTAR PRADESH
UNITED COLLEGE OF ENGINEERING & MANAGEMENT
UTTAR PRADESH
UNITED INSTITUTE OF TECHNOLOGY
UTTAR PRADESH
UNITED SCHOOL OF BUSINESS
UTTAR PRADESH
UNITED COLLEGE OF ENGINEERING & RESEARCH
UTTAR PRADESH
GCRG MEMORIAL TRUST'S GROUP OF INSTITUTIONS
UTTAR PRADESH
UNITED INSTITUTE OF MANAGEMENT
UTTAR PRADESH
SANSKRITI SCHOOL OF BUSINESS (SSB)
UTTAR PRADESH
BON MAHARAJ ENGINEERING COLLEGE
UTTAR PRADESH
N.C.R. TECHNICAL CAMPUS
UTTAR PRADESH
UNITED COLLEGE OF ENGINEERING & RESEARCH, GREATER NOIDA
UTTAR PRADESH
UNITED INSTITUTE OF MANAGEMENT (MBA)
UTTAR PRADESH
HIMALYAN INSTITUTE OF TECHNOLOGY AND MANAGEMENT
UTTAR PRADESH
APEX INSTITUTE OF TECHNOLOGY
UTTAR PRADESH
SHREE GANPATI INSTITUTE OF TECHNOLOGY
UTTAR PRADESH
BABU BANARASI DAS NATIONAL INSTITUTE OF TECHNOLOGY AND MANAGEMENT
UTTAR PRADESH
JRE GROUP OF INSTITUTIONS
UTTAR PRADESH
BHABHA COLLEGE OF ENGINEERING
UTTAR PRADESH
P.K.INSTITUTE OF TECHNOLOGY & MANAGEMENT
UTTAR PRADESH
PSIT-PRANVEER SINGH INSTITUTE OF TECHNOLOGY
UTTAR PRADESH
NARAINA VIDYA PEETH MANAGEMENT INSTITUTE
UTTAR PRADESH
ACN COLLEGE OF ENGG. & MANAGMENT STUDIES
UTTAR PRADESH
G L BAJAJ GROUP OF INSTITUTIONS
UTTAR PRADESH
BLS INSTITUTE OF MANAGEMENT
UTTAR PRADESH
JAIPURIA ISNTITUTE OF MANAGEMENT, LUCKNOW
UTTAR PRADESH
SHRI RAM MURTI SMARAK WOMEN'S COLLEGE OF ENGINEERING. & TECHNOLOGY
UTTAR PRADESH
FACULTY OF PG DEGREE IN BUSINESS ADMINISTRATION, R.B.S.COLLEGE, AGRA.
UTTAR PRADESH
MORADABAD INSTITUTE OF TECHNOLOGY
UTTAR PRADESH
SACRED HEART INSTITUTE OF MANAGEMENT & TECHNOLOGY
UTTAR PRADESH
ABES INSTITUTE OF TECHNOLOGY
UTTAR PRADESH
TRANSLAM INSTITUTE OF TECHNOLOGY AND MANAGEMENT
UTTAR PRADESH
HARISH CHANDRA POST GRADUATE COLLEGE, FACULTY OF MANAGEMENT
UTTAR PRADESH
KAMLA NEHRU INSTITUTE OF
UTTAR PRADESH
RAKSHPAL BAHADUR MANAGEMENT INSTITUTE, BAREILLY
UTTAR PRADESH
DOON COLLEGE OF ENGINEERING AND TECHNOLOGY, SUNDERPUR, SAHARANPUR
UTTAR PRADESH
DOON COLLEGE OF ENGINEERING AND TECHNOLOGY, SUNDERPUR, SAHARANPUR
UTTAR PRADESH
INSTITUTE OF MANAGEMENT SCIENCES
UTTAR PRADESH
GNIT MANAGEMENT SCHOOL
UTTAR PRADESH
MAHARAJA AGARSAIN INSTITUTE OF TECHNOLOGY
UTTAR PRADESH
SHARDA INSTITUTE OF MANAGEMENT & TECHNOLOGY
UTTAR PRADESH
JAIPURIA INSTITUTE OF MANAGEMENT, NOIDA
UTTAR PRADESH
ASIAN BUSINESS SCHOOL
UTTAR PRADESH
NAVNEET COLLEGE OF TECHNOLOGY & MANAGEMENT
UTTAR PRADESH
DR. VIRENDRA SWARUP INSTITUTE OF COMPUTER STUDIES
UTTAR PRADESH
IILM ACADEMY OF HIGHER LEARNING, LUCKNOW
UTTAR PRADESH
CENTRE FOR MANAGEMENT DEVELOPMENT
UTTAR PRADESH
INSTITUTE OF TECHNOLOGY & MANAGEMENT(341)
UTTAR PRADESH
B.N. COLLEGE OF ENGINEERING & TECHNOLOGY(BNCET)
UTTAR PRADESH
ACCMAN INSTITUTE OF MANAGEMENT
UTTAR PRADESH
IIMT COLLEGE OF ENGINEERING
UTTAR PRADESH
SKYLINE INSTITUTE OF MANAGEMENT & TECHNOLOGY
UTTAR PRADESH
HINDUSTAN INSTITUTE OF MANAGEMENT AND COMPUTER STUDIES
UTTAR PRADESH
ASHOKA INSTITUTE OF TECHNOLOGY AND MANAGEMENT
UTTAR PRADESH
PSIT COLLEGE OF ENGINEERING
UTTAR PRADESH
IIMT ENGINEERING COLLEGE
UTTAR PRADESH
BARAN INSTITUTE OF MANAGEMENT
UTTAR PRADESH
TRIVEDI INSTITUTE OF MANAGEMENT AND TECHNOLOGY
UTTAR PRADESH
DR. VIRENDRA SWARUP MEMORIAL TRUST GROUP OF INSTITUTION
UTTAR PRADESH
SARASWATI INSTITUTE OF ENGINEERING & TECHNOLOGY
UTTAR PRADESH
SHIVDAN SINGH INSTITUTE OF TECHNOLOGY & MANAGEMENT
UTTAR PRADESH
R. R. INSTITUTE OF MODERN TECHNOLOGY
UTTAR PRADESH
ASIAN COLLEGE OF MANAGEMENT
UTTAR PRADESH
MAHAVEER INSTITUTE OF TECHNOLOGY
UTTAR PRADESH
BANSAL INSTITUTE OF ENGINEERING AND TECNOLOGY
UTTAR PRADESH
RAJSHREE INSTITUTE OF MANAGEMENT & TECHNOLOGY
UTTAR PRADESH
JAIPURIA INSTITUTE OF MANAGEMENT STUDIES
UTTAR PRADESH
HI-TECH INSTITUTE OF ENGINEERING & TECHNOLOGY
UTTAR PRADESH
IIMT COLLEGE OF MANAGEMENT
UTTAR PRADESH
GOEL INSTITUTE OF TECHNOLOGY & MANAGEMENT
UTTAR PRADESH
INTERNATIONAL INSTITUTE FOR SPECIAL EDUCATION
UTTAR PRADESH
AGRA PUBLIC COLLEGE OF TECH.& MANAGEMENT
UTTAR PRADESH
PRINCE INSTITUTE OF INNOVATIVE TECHNOLOGY GR. NOIDA
UTTAR PRADESH
ACCURATE INSTITUTE OF MANAGEMENT & TECHNOLOGY
UTTAR PRADESH
NANDINI NAGAR TECHNICAL CAMPUS
UTTAR PRADESH
NORTHERN INSTITUTE FOR INTEGRATED LEARNING IN MANAGEMENT (NIILM)
UTTAR PRADESH
JAHANGIRABAD EDUCATIONAL TRUST GROUP OF INSTITUTIONS
UTTAR PRADESH
SHRI JEET RAM SMARAK INSTITUTE OF ENGINEERING & TECHNOLOGY
UTTAR PRADESH
INSTITUTE OF ADVANCED MANAGEMENT AND RESERCH
UTTAR PRADESH
SHIVAM TECHNICAL CAMPUS
UTTAR PRADESH
PREM PRAKASH GUPTA INSTITUTE OF MANAGEMENT
UTTAR PRADESH
VIDYA SCHOOL OF BUSINESS
UTTAR PRADESH
DAYANAND DINANATH INSTITUTE OF TECHNOLOGY (DDIT)
UTTAR PRADESH
NARVADESHWAR MANAGEMENT COLLEGE
UTTAR PRADESH
SETH JAIPRAKASH MUKANDLAL POLYTECHNIC
UTTAR PRADESH
RAMESH CHAND INSTITUTE OF MANAGEMENT(RCIM)
UTTAR PRADESH
SITAPUR SHIKSHA SANSTHAN GROUP OF INSTITUTIONS
UTTAR PRADESH
JANHIT SCHOOL OF MANAGEMENT
UTTAR PRADESH
JANHIT INSTITUTE OF EDUCATION & INFORMATION
UTTAR PRADESH
IIMT PROFESSIONAL COLLEGE
UTTAR PRADESH
VIVEKANAND INSTITUTE OF TECHNOLOGY & SCIENCE
UTTAR PRADESH
KHANDELWAL COLLEGE OF MANAGEMENT SCIENCE AND TECHNOLOGY (PGDM)
UTTAR PRADESH
SATYAM COLLEGE OF MANAGEMENT
UTTAR PRADESH
ESHAN COLLEGE OF MANAGEMENT
UTTAR PRADESH
BHAGWANT INSTITUTE OF TECHNOLOGY
UTTAR PRADESH
C-MAT BUSINESS SCHOOL
UTTAR PRADESH
B.N.DEGREE COLLEGE
UTTAR PRADESH
LUCKNOW MODEL INSTITUTE OF MANAGEMENT
UTTAR PRADESH
NOIDA INSTITUTE OF ENGINEERING AND TECHNOLOGY (MCA INSTITUTE)
UTTAR PRADESH
VISION INSTITUTE OF MANAGEMENT
UTTAR PRADESH
NEELKANTH INSTITUTE OF TECHNOLOGY
UTTAR PRADESH
DEEN DAYAL COLLEGE OF MANAGEMENT
UTTAR PRADESH
TOWN POLYTECHNIC,BALLIA
UTTAR PRADESH
MAHARANA PRATAP ENGINEERING COLLEGE
UTTAR PRADESH
R.N COLLEGE OF MANAGEMENT
UTTAR PRADESH
I.T.S - INSTITUTE OF MANAGEMENT
UTTAR PRADESH
FIVE SCHOOL OF BUSINESS
UTTAR PRADESH
ACCURATE INSTITUTE OF MANAGEMENT & TECHNOLOGY
UTTAR PRADESH
KIPM-COLLEGE OF MANAGEMENT
UTTAR PRADESH
BANSHI COLLEGE OF MANAGEMENT STUDIES
UTTAR PRADESH
CHANDRA MAULI INSTITUTE OF MANAGEMENT SCIENCES & TECHNOLOGY
UTTAR PRADESH
DEEN DAYAL UPADHYAY GORAKHPUR UNIVERSITY
UTTAR PRADESH
SANJAY INSTITUTE OF ENGINEERING & MANAGEMENT
UTTAR PRADESH
INSTITUTE OF PRODUCTIVITY & MANAGEMENT, KANPUR
UTTAR PRADESH
SHREE BANKEY BIHARI INSTITUTE OF MANAGEMENT
UTTAR PRADESH
ITM SCHOOL OF MANAGEMENT
UTTAR PRADESH
DEVENDER SINGH INSTITUTE OF TECHNOLOGY AND MANAGEMENT
UTTAR PRADESH
HMFA MEMORIAL INSTITUTE OF ENGG & TECH.
UTTAR PRADESH
NOIDA INSTITUTE OF ENGINEERING & TECHNOLOGY
UTTAR PRADESH
ADVANCE INSTITUTE OF MANAGEMENT
UTTAR PRADESH
NEELAM COLLEGE OF ENGINEERING & TECHNOLOGY
UTTAR PRADESH
GOEL INSTITUTE OF HIGHER STUDIES
UTTAR PRADESH
NIMT INSTITUTE OF HOSPITAL AND PHARMA MANAGEMENT
UTTAR PRADESH
SHREE SATYA INSTITUTE OF MANAGEMENT (MBA)
UTTAR PRADESH
KANPUR INSTITUTE OF TECHNOLOGY
UTTAR PRADESH
MADHU VACHASPATI SCHOOL OF MANAGEMENT
UTTAR PRADESH
SRIRAM INSTITUTE OF MANAGEMENT & TECHNOLOGY
UTTAR PRADESH
BRAHMANAND GROUP OF INSTITUTIONS
UTTAR PRADESH
NIMT GREATER NOIDA
UTTAR PRADESH
NIMT INSTITUTE OF TECHNOLOGY AND MANAGEMENT
UTTAR PRADESH
A.N.A COLLEGE OF MANAGEMENT STUDIES
UTTAR PRADESH
M.D. COLLEGE, AGRA
UTTAR PRADESH
JAGRAN INSTITUTE OF MANAGEMENT
UTTAR PRADESH
SUBHARTI INSTITUTE OF TECHNOLOGY AND ENGINEERING
UTTAR PRADESH
SURYA SCHOOL OF PLANNING & ENGINEERING MANAGEMENT
UTTAR PRADESH
S.P.C.J. INSTITUTE OF MANAGEMENT
UTTAR PRADESH
INDRADEV INSTITUTE OF EDUCATION & TECHNOLOGY
UTTAR PRADESH
GYAN INSTITUTE OF MANAGEMENT & TECHNOLOGY
UTTAR PRADESH
GYAN INSTITUTE OF MANAGEMENT & TECHNOLOGY
UTTAR PRADESH
INTEGRATED ACADEMY OF MANAGEMENT AND TECHNOLOGY
UTTAR PRADESH
INSTITUTE OF PRODUCTIVITY & MANAGEMENT, GHAZIABAD
UTTAR PRADESH
INSTITUTE OF MANAGEMENT & RESEARCH
UTTAR PRADESH
SHAMBHUNATH INSTITUTE OF MANAGEMENT
UTTAR PRADESH
SHAMBHUNATH INSTITUTE OF ENGINEERING & TECHNOLOGY
UTTAR PRADESH
SURYA COLLEGE OF BUSINESS MANAGEMENT
UTTAR PRADESH
JANTA POLYTECHNIC JAHANGIRABAD
UTTAR PRADESH
SIR MADANLAL INSTITUTE OF MANAGEMENT
UTTAR PRADESH
DISHA BHARTI COLLEGE OF MANAGEMENT AND EDUCATION
UTTAR PRADESH
STUDIES & RESEARCH (IPSR)
UTTAR PRADESH
D.N.S. COLLEGE OF ENGINEERING & TECHNOLOGY
UTTAR PRADESH
INSTITUTE OF MANAGEMENT SCIENCES
UTTAR PRADESH
GYAN BHARTI INSTITUTE OF TECHNOLOGY
UTTAR PRADESH
INSTITUTE OF MANAGEMENT STUDIES, MAHATMA GANDHI KASHI VIDYAPITH
UTTAR PRADESH
SP MEMORIAL INSTITUTE TECHNOLOGY
UTTAR PRADESH
MEERUT INTERNATIONAL INSTITUTE OF TECHNOLOGY
UTTAR PRADESH
KUNWAR HARIBANSH SINGH INSTITUTE OF MANAGEMENT
UTTAR PRADESH
GOVT. GIRLAS POLYTECHNIC, AMETHI
UTTAR PRADESH
UNIQUE INSTITUTE OF MANAGEMENT & TECHNOLOGY (MCA)
UTTAR PRADESH
INSTITUTE OF INFORMATION MANAGEMENT & TECHNOLOGY, ALIGARH
UTTAR PRADESH
ABHINAVA INSTITUTE OF MANAGEMENT AND TECHNOLOGY
UTTAR PRADESH
INSTITUTE OF PRODUCTIVITY & MANAGEMENT
UTTAR PRADESH
MANAGEMENT(DRONACHARYA GROUP OF INSTITUTIONS)
UTTAR PRADESH
SAVITRI BAI PHULE GOVERMENT GIRLS POLYTECHNIC
UTTAR PRADESH
INSTITUTE OF ENGINEERING AND TECHNOLOGY
UTTAR PRADESH
KANPUR INSTITUTE OF MANAGEMENT STUDIES
UTTAR PRADESH
HARDAYAL TECHNICAL CAMPUS
UTTAR PRADESH

SETH VISHAMBHAR NATH INSTITUTE OF MANAGEMENT STUDIES & RESEARCH
UTTAR PRADESH
RAJ KUMAR GOEL INSTITUTE OF TECHNOLOGY FOR WOMEN
UTTAR PRADESH
INSTITUTE OF INFORMATION MANAGEMENT AND TECHNOLOGY
UTTAR PRADESH
RAJARSHI SCHOOL OF MANAGEMENT AND TECHNOLOGY
UTTAR PRADESH
NARAINA VIDYA PEETH GROUP OF INSTITUTIONS
UTTAR PRADESH
PRIYADARSHINI COLLEGE OF COMPUTER SCIENCES
UTTAR PRADESH
INSTITUTE OF PLANNING & MANAGEMENT
UTTAR PRADESH
GOVT. GIRLS POLYTECHNIC
UTTAR PRADESH
S.R.M. BUSINESS SCHOOL
UTTAR PRADESH
DEWAN V.S. INSTITUTE OF MARKETING MANAGEMENT
UTTAR PRADESH
DWARIKADHEESH RESEARCH EDUCATION AND MANAGEMENT SCHOOL
UTTAR PRADESH
INDIRA GANDHI INSTITUTE OF CO- OPERATIVE MANAGEMENT
UTTAR PRADESH
SAROJ INSTITUTE OF TECHNOLOGY & MANAGEMENT
UTTAR PRADESH
SETH VISHAMBHAR NATH INSTITUTE OF ENGINEERING & TECHNOLOGY
UTTAR PRADESH
INSTITUTE OF MANAGEMENT STUDIES SAHARANPUR
UTTAR PRADESH
SCHOOL OF BUSINESS MANAGEMENT& TECHNOLOGY
UTTAR PRADESH
PATRONAGE INSTITUTE OF MANAGEMENT STUDIES
UTTAR PRADESH
BHAVDIYA INSTITUTE OF BUSINESS MANAGEMENT
UTTAR PRADESH
MAHARANA PRATAAP COLLEGE OF ENGINEERING
UTTAR PRADESH
ITERC COLLEGE OF MANAGEMENT
UTTAR PRADESH
BORA INSTITUTE OF MANAGEMENT SCIENCES
UTTAR PRADESH
SHREE JEE BABA INSTITUTE OF PROFESSIONAL STUDIES
UTTAR PRADESH
SGM INSTITUTE OF MANAGEMENT
UTTAR PRADESH
CHARAK INSTITUTE OF BUSINESS MANAGEMENT
UTTAR PRADESH
SUBHASH INSTITUTE OF SOFTWARE TECHNOLOGY,KANPUR
UTTAR PRADESH
HARLAL INSTITUTE OF MANAGEMENT & TECHNOLOGY (HIMT)
UTTAR PRADESH
R. D. FOUNDATION GROUP OF INSTITUTIONS
UTTAR PRADESH
INSTITUTE OF PROFESSIONAL EXCELLENCE & MANAGEMENT
UTTAR PRADESH
VIDYA COLLEGE OF ENGINEERING
UTTAR PRADESH
TRIVENI INSTITUTE OF MANAGEMENT EDUCATION
UTTAR PRADESH
GOVERNMENT POLYTECHNIC,ORAI(JALAUN)
UTTAR PRADESH
GLOBAL INSTITUTE OF MANAGEMENT
UTTAR PRADESH
KRISHNNARIPT INSTITUTE OF MANAGEMENT & TECHNOLOGY
UTTAR PRADESH
SHANTI NIKETAN GROUP OF INSTITUTIONS
UTTAR PRADESH
SSLD VARSHNEY INSTITUTE OF MANAGEMENT & ENGINEERING
UTTAR PRADESH
MAA VAISHNO DEVI EDUCATIONAL & LAW COLLEGE
UTTAR PRADESH
DR. RAM MANOHAR LOHIA AVADH UNIVERSITY, FAIZABAD
UTTAR PRADESH
HLM BUSINESS SCHOOL
UTTAR PRADESH
RHANS COLLEGE OF MANAGEMENT
UTTAR PRADESH
UNNATI MANAGEMENT COLLEGE
UTTAR PRADESH
KCC INSTITUTE OF MANAGEMENT
UTTAR PRADESH
PT. SUJAN SINGH DEGREE COLLEGE
UTTAR PRADESH
ASIAN INSTITUTE OF ENGINEERING & TECHNOLOGY
UTTAR PRADESH
AUROUS INSTITUTE OF MANAGEMENT
UTTAR PRADESH
RAJENDRA PRASAD COLLEGE OF MANAGEMENT
UTTAR PRADESH
VINAYAK VIDYAPEETH
UTTAR PRADESH
BHARTI INSTITUTE OF MANAGEMENT AND TECHNOLOGY
UTTAR PRADESH
LAKSHYA INSTITUTE OF MANAGEMENT & INFORMATION TECHNOLOGY
UTTAR PRADESH
BRAJ INSTITUTE OF MANAGEMENT & TECHNOLOGY
UTTAR PRADESH
ACME INSTITUTE OF MANAGEMENT AND TECHNOLOGY
UTTAR PRADESH
SETH SRINIWAS AGARWAL INSTITUTE OF MANAGEMENT
UTTAR PRADESH
DEPARTMENT OF BUSINESS ADMINISTRATION, INSTITUTE OF MANAGEMENT STUDIES
UTTAR PRADESH
VIDYA INTERNATIONAL SCHOOL OF BUSINESS
UTTAR PRADESH
GREATER NOIDA INSTITUTE OF BUSINESS MANAGEMENT
UTTAR PRADESH
A.P.S.COLLEGE OF EDUCATION & TECHNOLOGY
UTTAR PRADESH
YASH RAJ INSTITUTE OF EDUCATION AND MANAGEMENT
UTTAR PRADESH
SHRI R.L.T. INSTITUTE OF MANAGEMENT
UTTAR PRADESH
RISHI CHADHA VISHVAS GIRLS INSTITUTE OF TECHNOLOGY,
UTTAR PRADESH
JAGMOHAN INSTITUTE OF MANAGEMENT & TECHNOLOGY
UTTAR PRADESH
GOVERNMENT POLYTECHNIC SAHARANPUR
UTTAR PRADESH
CENTRAL INSTITUTE OF MANAGEMENT & TECHNOLOGY
UTTAR PRADESH
RUDRA GROUP OF INSTITUTIONS
UTTAR PRADESH
DEPARTMENT OF BUSINESS ADMINISTRATION
UTTAR PRADESH
AXIS INSTITUTE OF PLANNING AND MANAGEMENT
UTTAR PRADESH
TRINITY COLLEGE FOR MANAGEMENT AND TECHNOLOGY
UTTAR PRADESH
KALKA ENGINEERING COLLEGE
UTTAR PRADESH
MAHAVEER INSTITUTE OF TECHNOLOGY & MANAGEMENT
UTTAR PRADESH
SHAMLI INSTITUTE OF ENGINEERING & TECHNOLOGY
UTTAR PRADESH
MAHARANA INSTITUTE OF TECHNOLOGY & SCIENCES
UTTAR PRADESH
VENKATESHWARA INSTITUTE OF TECHNOLOGY
UTTAR PRADESH
INSTITUTE OF MANAGEMENT RESEARCH AND TECHNOLOGY
UTTAR PRADESH
APOLLO INSTITUTE OF TECHNOLOGY
UTTAR PRADESH
K P COLLEGE OF MANAGEMENT
UTTAR PRADESH
BIRLA INSTITUTE OF TECHNOLOGY, MESRA, EXTENSION CENTER NOIDA
UTTAR PRADESH
NEELKANTH VIDYAPEETH
UTTAR PRADESH
SHREEJEE GOVERDHAN MAHARAJ COLLEGE OF PROFESSIONAL STUDIES
UTTAR PRADESH
AXIS BUSINESS SCHOOL
UTTAR PRADESH
IMS ENGINEERING COLLEGE
UTTAR PRADESH
MUZAFFARNAGAR INSTITUTE OF TECHNOLOGY
UTTAR PRADESH
RISHI INSTITUTE OF ENGINNERING AND TECHNOLOGY
UTTAR PRADESH
ADHUNIK INSTITUTE OF PRODUCTIVITY MANAGEMENT & RESEARCH
UTTAR PRADESH
KUNWAR SATYAVIRA COLLEGE OF ENGINEERING AND MANAGEMENT
UTTAR PRADESH
AJAY KUMAR GARG INSTITUTE OF MANAGEMENT
UTTAR PRADESH
ACCORD BUSINESS SCHOOL
UTTAR PRADESH
C.B.S COLLEGE OF MANAGEMENT
UTTAR PRADESH
ARYAKUL COLLEGE OF MANAGEMENT
UTTAR PRADESH
DR. OM PRAKASH INSTITUTE OF MANAGEMENT AND TECHNOLOGY
UTTAR PRADESH
UTTAR PRADESH VIKLANG UDDHAR DR. SHAKUNTALA MISRA VISHWAVIDYALAYA
UTTAR PRADESH
JANHIT GROUP OF INSTITUTIONS
UTTAR PRADESH
DEVPRAYAG INSTITUTE OF TECHNICAL STUDIES
UTTAR PRADESH
LDC INSTITUTE OF TECNICAL STUDIES
UTTAR PRADESH
TDL COLLEGE OF TECHNOLOGY & MANAGEMENT
UTTAR PRADESH
PRAKASHDEEP INSTITUTE OF MANAGEMENT & TECHNOLOGY
UTTAR PRADESH
UNITED INSTITUTE OF DESIGNING....
UTTAR PRADESH
INSTITUTE OF MANAGEMENT STUDIES, NOIDA
UTTAR PRADESH
MOTI LAL RASTOGI SCHOOL OF MANAGEMENT
UTTAR PRADESH
DEVPRAYAG INSTITUTE OF MANAGEMENT
UTTAR PRADESH
INSTITUTE OF ECONOMICS AND FINANCE
UTTAR PRADESH
DEEN DAYAL UPADHYAYA INSTITUTE OF MANGEMENT AND HIGHER STUDIES
UTTAR PRADESH
JYOTI COLLEGE OF MANAGEMENT SCIENCE & TECHNOLOGY
UTTAR PRADESH
SRAJAN INSTITUTE OF MANAGEMENT AND TECHNOLOGY
UTTAR PRADESH
KRS COLLEGE OF MANAGEMENT
UTTAR PRADESH
INSTITUTE OF COOPERATIVE AND CORPORATE MANAGEMENT
UTTAR PRADESH
IMS J.P. NAGAR
UTTAR PRADESH
CH. HARCHAND SINGH COLLEGE OF MANAGEMENT
UTTAR PRADESH
ACN SCHOOL OF BUSINESS
UTTAR PRADESH
JAIPURIA INSTITUTE OF MANAGEMENT
UTTAR PRADESH
TRIDENT ET GROUP OF INSTITUTIONS
UTTAR PRADESH
ANSAL TECHNICAL CAMPUS
UTTAR PRADESH
IDEAL INSTITUTE OF TECHNOLOGY
UTTAR PRADESH
KIET GROUP OF INSTITUTIONS
UTTAR PRADESH
BHABHA INSTITUTEOFTECHNOLOGY
UTTAR PRADESH
SHIVA INSTITUTE OF MANAGEMENT STUDIES, GHAZIABAD
UTTAR PRADESH
AASHLAR BUSINESS SCHOOL
UTTAR PRADESH
SHRI RAM GROUP OF COLLEGES
UTTAR PRADESH
INDUS BUSINESS ACADEMY
UTTAR PRADESH
UTTAM INSTITUTE OF MANAGEMENT STUDIES
UTTAR PRADESH
INSTITUTE OF MANAGEMENT EDUCATION
UTTAR PRADESH
GANESHI LAL BAJAJ INSTITUTE OF TECHNOLOGY AND MANAGEMENT
UTTAR PRADESH
SUNDER DEEP GROUP OF INSTITUTIONS
UTTAR PRADESH
ABHAY MEMORIAL TRUST GROUP OF INSTITUTIONS
UTTAR PRADESH
B.B.S. INSTITUTE OF MANAGEMENT TECHNOLOGY
UTTAR PRADESH
MIT GROUP OF INSTITUTIONS
UTTAR PRADESH
DRONACHARYA GROUP OF INSTITUTIONS
UTTAR PRADESH
SCHOOL OF MANAGEMENT SCIENCES
UTTAR PRADESH
JMS GROUP OF INSTITUTIONS
UTTAR PRADESH
BHAGWATI INSTITUTE OF TECHNOLOGY & SCIENCE
UTTAR PRADESH
HINDUSTAN INSTITUTE OF TECHNOLOGY AND MANAGEMENT
UTTAR PRADESH
TAKSILA BUSINESS SCHOOL
UTTAR PRADESH
ANAND ENGINEERING COLLEGE
UTTAR PRADESH
IEC GROUP OF INSTITUTIONS
UTTAR PRADESH
LUCKNOW INSTITUTE OF TECHNOLOGY, LUCKNOW
UTTAR PRADESH
MASTER SCHOOL OF MANAGEMENT
UTTAR PRADESH
ALIGARH COLLEGE OF ENGINEERING AND TECHNOLOGY
UTTAR PRADESH
BANSHI COLLEGE OF MANAGEMENT AND TECHNOLOGY
UTTAR PRADESH
MIT COLLEGE OF MANAGEMENT
UTTAR PRADESH
DR. GAUR HARI SINGHANIA INSTITUTE OF MANAGEMENT AND RESEARCH
UTTAR PRADESH
J.S. INSTITUTE OF MANAGEMENT AND TECHNOLOGY, SHIKOHABAD
UTTAR PRADESH
AKS MANAGEMENT COLLEGE
UTTAR PRADESH
MODINAGAR INSTITUTE OF TECHNOLOGY
UTTAR PRADESH
--><tr>
<td>VIVEKANANDA COLLEGE OF TECHNOLOGY & MANAGEMENT, ALIGARH</td>
<td>UTTAR PRADESH</td></td>
</tr>
<tr>
<td>S S INSTITUTE OF MANAGEMENT</td>
<td>UTTAR PRADESH</td></td>
</tr>
<tr>
<td>AZAD INSTITUTE OF ENGINEERING & TECHNOLOGY</td>
<td>UTTAR PRADESH</td></td>
</tr>
<tr>
<td>COLLEGE OF MANAGEMENT STUDIES</td>
<td>UTTAR PRADESH</td></td>
</tr>
<tr>
<td>DAYANAND ACADEMY OF MANAGEMENT STUDIES</td>
<td>UTTAR PRADESH</td></td>
</tr>
<tr>
<td>HARI INSTITUTE OF MANAGEMENT, SAHARANPUR</td>
<td>UTTAR PRADESH</td></td>
</tr>
<tr>
<td>GREATER NOIDA INSTITUTE OF TECHNOLOGY (MBA INSTITUTE)</td>
<td>UTTAR PRADESH</td></td>
</tr>
<tr>
<td>VIDYA BHAVAN COLLEGE FOR ENGINEERING TECHNOLOGY</td>
<td>UTTAR PRADESH</td></td>
</tr>
<tr>
<td>ARMY INSTITUTE OF MANAGEMENT & TECHNOLOGY</td>
<td>UTTAR PRADESH</td></td>
</tr>
<tr>
<td>KASHI INSTITUTE OF TECHNOLOGY</td>
<td>UTTAR PRADESH</td></td>
</tr>
<tr>
<td>INJ BUSINESS SCHOOL</td>
<td>UTTAR PRADESH</td></td>
</tr>
<tr>
<td>H.R.C.T. GROUP OF INSTITUTIONS</td>
<td>UTTAR PRADESH</td></td>
</tr>
<tr>
<td>UTKARSH COLLEGE OF MANAGEMENT EDUCATION</td>
<td>UTTAR PRADESH</td></td>
</tr>
<tr>
<td>AMBALIKA INSTITUTE OF MANAGEMENT AND TECHNOLOGY</td>
<td>UTTAR PRADESH</td></td>
</tr>
<tr>
<td>GLOBAL EDUCATIONAL & WELFARE SOCIETY GROUP OF INSTITUTIONS</td>
<td>UTTAR PRADESH</td></td>
</tr>
<tr>
<td>IIMT MANAGEMENT COLLEGE</td>
<td>UTTAR PRADESH</td>
</tr>
<tr>
<td>A R INSTITUTE OF MANAGEMENT & TECHNOLOGY</td>
<td>UTTAR PRADESH</td>
</tr>
<tr>
<td>BABU BANARSI DAS INSTITUTE OF TECHNOLOGY</td>
<td>UTTAR PRADESH</td>
</tr>
<tr>
<td>INSITITUTE OF MANAGEMENT TECHNOLOGY, GHAZIABAD</td>
<td>UTTAR PRADESH</td>
</tr>
<tr>
<td>IILM GRADUATE SCHOOL OF MANAGEMENT</td>
<td>UTTAR PRADESH</td>
</tr>
<tr>
<td>SANSKAAR COLLEGE OF MANAGEMENT AND COMPUTER APPLICATIONS</td>
<td>UTTAR PRADESH</td>
</tr>
<tr>
<td>KRISHNA GIRLS ENGG. COLLEGE</td>
<td>UTTAR PRADESH</td>
</tr>
<tr>
<td>PRATAP COLLEGE OF MANAGEMENT</td>
<td>UTTAR PRADESH</td>
</tr>
<tr>
<td>DR. RIZVI COLLEGE OF ENGINEERING</td>
<td>UTTAR PRADESH</td>
</tr>
<tr>
<td>DAYANAND DINANATH COLLEGE OF MANAGEMENT</td>
<td>UTTAR PRADESH</td>
</tr>
<tr>
<td>DISHA INSTITUTE OF SCIENCE & TECHNOLOGY</td>
<td>UTTAR PRADESH</td>
</tr>
<tr>
<td>B.B.S. COLLEGE OF ENGINEERING & TECHNOLOGY</td>
<td>UTTAR PRADESH</td>
</tr>
<tr>
<td>JP INSTITUTE OF MANAGEMENT IN IT & MARKETING</td>
<td>UTTAR PRADESH</td>
</tr>
<tr>
<td>NORTH INDIA INSTITUTE OF TECHNOLOGY</td>
<td>UTTAR PRADESH</td>
</tr>
<tr>
<td>S.D.COLLEGE OF MANAGEMENT STUDIES</td>
<td>UTTAR PRADESH</td>
</tr>
<tr>
<td>RV NORTH LAND INSTITUTE OF MANAGEMENT</td>
<td>UTTAR PRADESH</td>
</tr>
<tr>
<td>DR. M.C. SAXENA COLLEGE OF ENGINEERING & TECHNOLOGY</td>
<td>UTTAR PRADESH</td>
</tr>
<tr>
<td>NCR BUSINESS SCHOOL</td>
<td>UTTAR PRADESH</td>
</tr>
<tr>
<td>APEEJAY INSTITUTE OF TECHNOLOGY: SCHOOL OF MANAGEMENT</td>
<td>UTTAR PRADESH</td>
</tr>
<tr>
<td>RAJ SCHOOL OF MANAGEMENT SCIENCES</td>
<td>UTTAR PRADESH</td>
</tr>
<tr>
<td>FUTURE INSTITUTE OF MANAGEMENT & TECHNOLOGY</td>
<td>UTTAR PRADESH</td>
</tr>
<tr>
<td>MANGALMAY INSTITUTE OF MANAGEMENT & TECHNOLOGY</td>
<td>UTTAR PRADESH</td>
</tr>
<tr>
<td>BHARAT INSTITUTE OF TECHNOLOGY (SCHOOL OF COMPUTER APPLICATION)</td>
<td>UTTAR PRADESH</td>
</tr>
<tr>
<td>SUNDER DEEP COLLEGE OF ENGINEERING & TECHNOLOGY</td>
<td>UTTAR PRADESH</td>
</tr>
<tr>
<td>RSD ACADEMY (COLLEGE OF MANAGEMENT & TECHNOLOGY)</td>
<td>UTTAR PRADESH</td>
</tr>
<tr>
<td>ARYABHATT COLLEGE OF ENGINEERING & TECHNOLOGY</td>
<td>UTTAR PRADESH</td>
</tr>
<tr>
<td>JHUNJHUNWALA INSTITUTE OF MANAGEMENT & TECHNOLOGY</td>
<td>UTTAR PRADESH</td>
</tr>
<tr>
<td>PRASAD INSTITUTE OF TECHNOLOGY</td>
<td>UTTAR PRADESH</td>
</tr>
<tr>
<td>KALI CHARAN NIGAM INSTITUTE OF TECHNOLOGY</td>
<td>UTTAR PRADESH</td>
</tr>
<tr>
<td>ITM-FHRAI INSTITUTE OF HOSPITALITY & MANAGEMENT</td>
<td>UTTAR PRADESH</td>
</tr>
<tr>
<td>CHRIST INSTITUTE OF MANAGEMENT GHAZIABAD</td>
<td>UTTAR PRADESH</td>
</tr>
<tr>
<td>KRISHNA COLLEGE OF MANAGEMENT</td>
<td>UTTAR PRADESH</td>
</tr>
<tr>
<td>SIS BUSINESS SCHOOL</td>
<td>UTTAR PRADESH</td>
</tr>
<tr>
<td>JBS INSTITUTE</td>
<td>UTTAR PRADESH</td>
</tr>
<tr>
<td>M.G. INSTITUTE OF MANAGEMENT & TECHNOLOGY</td>
<td>UTTAR PRADESH</td>
</tr>
<tr>
<td>SHRI SAI COLLEGE OF EDUCATION</td>
<td>UTTAR PRADESH</td>
</tr>
<tr>
<td>DAYAL GROUP OF INSTITUTION</td>
<td>UTTAR PRADESH</td>
</tr>
<tr>
<td>CENTRE FOR MANAGEMENT TECHNOLOGY</td>
<td>UTTAR PRADESH</td>
</tr>
<tr>
<td>LAL BAHADUR SHASTRI NATIONAL ACADEMY OF ADMINISTRATION</td>
<td>UTTARAKHAND</td>
</tr>
<tr>
<td>DEV BHOOMI INSTITUTE OF TECHNOLOGY & ENGINEERING</td>
<td>UTTARAKHAND</td>
</tr>
<tr>
<td>SHRIRAM INSTITUTE OF MANAGEMENT & TECHNOLOGY PG COLLEGE</td>
<td>UTTARAKHAND</td>
</tr>
<tr>
<td>OMKARANANDA INSTITUTE OF MANAGEMENT AND TECHNOLOGY</td>
<td>UTTARAKHAND</td>
</tr>
<tr>
<td>DOON INSTITUTE OF MANAGEMENT AND TECHNOLOGY</td>
<td>UTTARAKHAND</td>
</tr>
<tr>
<td>SATYENDRA CHANDRA GURIA INSTITUTE OF MANAGEMENT ANDTECHNOLOGY</td>
<td>UTTARAKHAND</td>
</tr>
<tr>
<td>GURUKUL KANGRI VISHWAVIDYALAYA</td>
<td>UTTARAKHAND</td>
</tr>
<tr>
<td>UPES INSTITUTE OF MANAGEMENT</td>
<td>UTTARAKHAND</td>
</tr>
<tr>
<td>MODERN INSTITUTE OF TECHNOLOGY</td>
<td>UTTARAKHAND</td>
</tr>
<tr>
<td>DOON BUSINESS SCHOOL</td>
<td>UTTARAKHAND</td>
</tr>
<tr>
<td>GURU NANAK EDUCATION TRUST'S GROUP OF INSTITUTION</td>
<td>UTTARAKHAND</td>
</tr>
<tr>
<td>SHRI GURU RAM RAI INSTITUTE OF MANAGEMENT</td>
<td>UTTARAKHAND</td>
</tr>
<tr>
<td>SARASWATI INSTITUTE OF MANAGEMENT & TECHNOLOGY</td>
<td>UTTARAKHAND</td>
</tr>
<tr>
<td>TULAS INSTITUTE</td>
<td>UTTARAKHAND</td>
</tr>
<tr>
<td>GURU RAM DAS INSTITUTE OF MANAGEMENT & TECHNOLOGY</td>
<td>UTTARAKHAND</td>
</tr>
<tr>
<td>INSTITUTE OF COOPERATIVE MANAGEMENT</td>
<td>UTTARAKHAND</td>
</tr>
<tr>
<td>DEV BHOOMI INSTITUTE OF TECHNOLOGY</td>
<td>UTTARAKHAND</td>
</tr>
<tr>
<td>ACADEMY OF MANAGEMENT STUDIES</td>
<td>UTTARAKHAND</td>
</tr>
<tr>
<td>SURAJMAL AGRAWAL GIRLS COLLEGE OF MANAGEMENT</td>
<td>UTTARAKHAND</td>
</tr>
<tr>
<td>COLLEGE OF ENGINEERING ROORKEE</td>
<td>UTTARAKHAND</td>
</tr>
<tr>
<td>BFIT TECHNICAL CAMPUS DEHRADUN</td>
<td>UTTARAKHAND</td>
</tr>
<tr>
<td>DOON BUSINESS SCHOOL GLOBAL</td>
<td>UTTARAKHAND</td>
</tr>
<tr>
<td>PHONICS GROUP OF INSTITUTIONS</td>
<td>UTTARAKHAND</td>
</tr>
<tr>
<td>NIMBUS ACADEMY OF MANAGEMENT</td>
<td>UTTARAKHAND</td>
</tr>
<tr>
<td>WALI GRAMODYOG VIKAS SANSTHAN'S GROUP OF INSTITUTIONS</td>
<td>UTTARAKHAND</td>
</tr>
<tr>
<td>AMRAPALI INSTITUTE OF MANAGEMENT & COMPUTER APPLICATIONS</td>
<td>UTTARAKHAND</td>
</tr>
<tr>
<td>QUANTUM SCHOOL OF BUSINESS</td>
<td>UTTARAKHAND</td>
</tr>
<tr>
<td>RAMANAND INSTITUTE OF PHARMACYAND MANAGEMENT</td>
<td>UTTARAKHAND</td>
</tr>
<tr>
<td>DEPARTMENT OF MANAGEMENT STUDIES, KUMAUN UNIVERSITY CAMPUS, BHIMTAL</td>
<td>UTTARAKHAND</td>
</tr>
<tr>
<td>BEEHIVE COLLEGE OF MANAGEMENT & TECHNOLOGY</td>
<td>UTTARAKHAND</td>
</tr>
<tr>
<td>SWAMI DARSHNANANDA INSTITUTE OF MANAGEMENT AND TECHNOLOGY</td>
<td>UTTARAKHAND</td>
</tr>
<tr>
<td>INSTITUTE OF MANAGEMENT STUDIES, ROORKEE</td>
<td>UTTARAKHAND</td>
</tr>
<tr>
<td>INSTITUTE OF MANAGEMENT STUDIES, ROORKEE</td>
<td>UTTARAKHAND</td>
</tr>
<tr>
<td>ROORKEE INSTITUTE OF TECHNOLOGY</td>
<td>UTTARAKHAND</td>
</tr>
<tr>
<td>COER SCHOOL OF MANAGEMENT</td>
<td>UTTARAKHAND</td>
</tr>
<tr>
<td>SHREE DEV BHOOMI INSTITUTE OF EDUCATION SCIENCE & TECHNOLOGY</td>
<td>UTTARAKHAND</td>
</tr>
<tr>
<td>ROORKEE COLLEGE OF MANAGEMENT & COMPUTER APPLICATIONS ROORKEE.</td>
<td>UTTARAKHAND</td>
</tr>
<tr>
<td>BISHAMBER SAHAI MANAGEMENT INSTITUTE</td>
<td>UTTARAKHAND</td>
</tr>
<tr>
<td>OM BIO SCIENCES & MANAGEMENT COLLEGE</td>
<td>UTTARAKHAND</td>
</tr>
<tr>
<td>B. S. NEGI MAHILA PRAVIDHIK PRASHIKSHAN SANSTHAN</td> 
<td>UTTARAKHAND</td>
</tr>
</tbody> 
</table>

</div>

<div class="tab-pane" id="step3">
<h4 class="tabpane-head1">Colleges of MBA</h4>

<table class="table table-striped mx-table">
 
<tbody>
</tbody><thead> 
<tr> 
<th>COLLEGE NAME</th> 
<th>Location</th> 
</tr> 
</thead> 

<tbody>
<tr>
<td>MOTILAL NEHRU NATIONAL INSTITUTE OF TECHNOLOGY</td>
<td>ALLAHABAD</td>
</tr>
<tr>
<td>UNIVERSITY BUSINESS SCHOOL</td>
<td>CHANDIGARH</td>
</tr>
<tr>
<td>LOVELY UNIVERSITY OF MANAGEMENT</td>
<td>PHAGWARA</td>
</tr>
<tr>
<td>INDIAN INSTITUTE OF MANAGEMENT</td>
<td>ROHTAK</td>
</tr>
<tr>
<td>MANAV RACHNA INTERNATIONAL UNIVERSITY</td>
<td>FARIDABAD</td>
</tr>
<tr>
<td>D.A.V INSTITUTE OF MANAGEMENT</td>
<td>FARIDABAD</td>
</tr>
<tr>
<td>DOON BUSINESS SCHOOL</td>
<td>DEHRADUN</td>
</tr>
<tr>
<td>ICFAI UNIVERSITY</td>
<td>DEHRADUN</td>
</tr>
<tr>
<td>CHITKARA BUSINESS SCHOOL</td>
<td>CHANDIGARH</td>
</tr>
<tr>
<td>GIAN JYOTI INSTITUTE OF MANAGEMENT AND TECHNOLOGY</td>
<td>MOHALI</td>
</tr>
<tr>
<td>DEPARTMENT OF INDUSTRIAL AND MANAGEMENT ENGINEERING</td>
<td>KANPUR</td>
</tr>
<tr>
<td>GURUNANAKDEV UNIVERSITY</td>
<td>AMRITSAR</td>
</tr>
<tr>
<td>INSTITUTE OF MANAGEMENT STUDIES</td>
<td>ROORKIE</td>
</tr>
<tr>
<td>BIRLA INSTITUTE OF TECHNOLOGY AND SCIENCE</td>
<td>PILANI</td>
</tr>
<tr>
<td>YMCA UNIVERSITY OF SCIENCE AND TECHNOLOGY</td>
<td>FARIDABAD</td>
</tr>
<tr>
<td>VAISH COLLEGE OF ENGINEERING</td>
<td>ROHTAK</td>
</tr>
<tr>
<td>INDIAN SCHOOL OF BUSINESS</td>
<td>HYDERABAD</td>
</tr>
<tr>
<td>ICFAI BUSINESS SCHOOL</td>
<td>HYDERABAD</td>
</tr>
<tr>
<td>NATIONAL INSTITUTE OF AGRI EXT MANAGEMENT</td>
<td>HYDERABAD</td>
</tr>
<tr>
<td>INDIAN INSTITUTE OF MANAGEMENT</td>
<td>BANAGALORE</td>
</tr>
<tr>
<td>DEPARTMENT OF MANAGEMENT STUDIES</td>
<td>BANAGLORE</td>
</tr>
<tr>
<td>TA PAI MANAGEMENT STUDIES</td>
<td>MANIPAL</td>
</tr>
<tr>
<td>LOYOLA INSTITUTE OF BUSINESS ADMINISTRATION</td>
<td>CHENNAI</td>
</tr>
<tr>
<td>DEPARTMENT OF MANAGEMENT STUDIES</td>
<td>MADRAS</td>
</tr>
<tr>
<td>INSTITUTE OF FINANACIAL MANAGEMENT AND RESEARCH</td>
<td>CHENNAI</td>
</tr>
<tr>
<td>INDIAN INSTITUTE OF MANAGEMENT</td>
<td>KOZHIKODHE</td>
</tr>
<tr>
<td>SCHOOL OF COMMUNICATION AND MANAGEMENT STUDIES</td>
<td>COCHIN</td>
</tr>
<tr>
<td>DC SCHOOL OF MANAGEMENT AND TECH</td>
<td>PULLIKKANAM</td>
</tr>
<tr>
<td>RAJAGIRI BUSINESS SCHOOL</td>
<td>COCHIN</td>
</tr>
<tr>
<td>SCHOOL OF MANAGEMENT</td>
<td>PONDICHERRY</td>
</tr>
<tr>
<td>INDIAN INSTITUTE OF MANAGEMENT</td>
<td>AHMEDABAD</td>
</tr>
<tr>
<td>INSTITUTE OF RURAL MANAGEMENT</td>
<td>ANAND</td>
</tr>
<tr>
<td>INSTITUTE OF MANAGEMENT ,NIRMA UNIVERSITY</td>
<td>AHMEDABAD</td>
</tr>
<tr>
<td>SP JAIN INSTITUTE OF MANAGEMENT AND RESEARCH</td>
<td>MUMBAI</td>
</tr>
<tr>
<td>SHAILESH J MEHTA SCHOOL OF MANAGEMENT</td>
<td>IIT BOMBAY</td>
</tr>
<tr>
<td>NATIONAL INSTITUTE OF INDUSTRIAL ENGINEERING</td>
<td>MUMBAI</td>
</tr>
<tr>
<td>GOA INSTITUTE OF MANAGEMENT</td>
<td>PANAJI</td>
</tr>
<tr>
<td>GOA INSTITUTE OF MANAGEMENT</td>
<td>PANAJI</td>
</tr>
</tbody> 
</table>

</div>

</div>

</div>

</div>

</div>

</div> 
</div>
</div>





<?php include('footer.php');?>
